-- ============================================================
-- ADAM BRAIN SEED V2 — EXPANDED
-- Adds 10x more market areas, rehab costs, knowledge, templates
-- ============================================================

-- ── ADDITIONAL MARKET AREAS — HILLSBOROUGH DEEP ─────────────
INSERT INTO market_areas (county,city,zip_code,median_sale_price,avg_price_per_sqft,avg_rent_3br,avg_rent_2br,hud_fmr_3br,avg_days_on_market,months_of_inventory,list_to_sale_ratio,investor_buyer_pct,flood_zone_prevalence,yoy_appreciation_pct,competition_level,ccg_priority,ccg_notes) VALUES
('Hillsborough','Tampa','33604',298000,178,1900,1580,2533,19,1.7,0.97,32,'medium',8.5,'high','secondary','Seminole Heights. Trendy area, rising ARVs. More investor activity. Good flip exit to urban buyers.'),
('Hillsborough','Tampa','33605',255000,158,1750,1450,2533,23,2.1,0.96,38,'medium',7.0,'watch','Ybor City adjacent. Some gentrification. Inconsistent market. Only very sharp deals.'),
('Hillsborough','Tampa','33606',485000,290,2800,2300,2533,15,1.3,0.99,15,'low',14.0,'secondary','Hyde Park/Davis Islands. Very high prices. CCG criteria hard to hit but monitor for distress.'),
('Hillsborough','Tampa','33609',420000,245,2500,2100,2533,16,1.4,0.99,18,'low',12.5,'secondary','South Tampa premium. Buyer demand extremely strong but prices make MAO math hard.'),
('Hillsborough','Tampa','33611',395000,235,2400,2000,2533,16,1.4,0.98,20,'low',11.8,'secondary','South Tampa. Ballast Point area. Good retail exit but high entry prices.'),
('Hillsborough','Tampa','33612',235000,145,1680,1380,2533,24,2.3,0.96,36,'low',7.0,'primary','North Tampa inland. Older stock. Less competition. CBS homes from 1960-1985. Worth watching.'),
('Hillsborough','Tampa','33613',248000,150,1720,1420,2533,23,2.2,0.96,34,'low',7.5,'primary','Carrollwood area. Good middle-market. Some wholesale deals come through here.'),
('Hillsborough','Tampa','33614',228000,142,1660,1360,2533,25,2.4,0.95,38,'medium',6.5,'watch','Broader North Tampa. Mixed quality. Some flood concerns. Selectively worth pursuing.'),
('Hillsborough','Tampa','33615',295000,175,1900,1570,2533,20,1.9,0.97,30,'medium',8.8,'watch','Northwest Tampa. Airport area. Some good deals but flood zone risk near Tampa Bay.'),
('Hillsborough','Tampa','33617',252000,153,1730,1430,2533,22,2.1,0.96,35,'low',7.5,'primary','Temple Terrace area. USF corridor. Strong rental demand from university. Good BRRRR territory.'),
('Hillsborough','Tampa','33619',228000,140,1650,1360,2533,25,2.4,0.95,40,'medium',6.0,'watch','East Tampa. Higher crime in some areas. Know your blocks. Some deals exist.'),
('Hillsborough','Temple Terrace','33637',278000,162,1830,1510,2533,21,2.0,0.97,32,'low',8.0,'primary','Temple Terrace proper. USF proximity. Good rental demand. CBS stock from 70s-90s.'),
('Hillsborough','Lutz','33548',482000,235,2500,2100,2533,14,1.3,0.99,18,'low',13.8,'secondary','Premium Lutz. Very strong market but very hard to make MAO work. Only exceptional deals.'),
('Hillsborough','Lutz','33549',392000,195,2200,1850,2533,16,1.5,0.98,22,'low',11.5,'secondary','East Lutz. Slightly more affordable than 33548. Some deals possible near CCG criteria.'),
('Hillsborough','Wimauma','33598',268000,143,1740,1430,2533,24,2.3,0.96,35,'low',7.0,'watch','South Hillsborough rural. Growing but slow market. Some good buys available.'),

-- ── ADDITIONAL MARKET AREAS — PINELLAS EXPANDED ─────────────
('Pinellas','St. Petersburg','33701',388000,225,2300,1900,1978,16,1.4,0.99,22,'medium',12.0,'secondary','Downtown St Pete. Very hot. Condo market strong. SFR flips work but prices are high.'),
('Pinellas','St. Petersburg','33703',312000,188,2000,1660,1978,18,1.6,0.98,28,'medium',9.5,'secondary','NE St Pete. Good market. Some flood near water. Inland areas are safer plays.'),
('Pinellas','St. Petersburg','33705',262000,161,1800,1490,1978,21,1.9,0.97,34,'medium',7.8,'secondary','South St Pete. More affordable. Some investment deals come through.'),
('Pinellas','St. Petersburg','33711',275000,167,1850,1530,1978,21,2.0,0.97,32,'medium',8.2,'secondary','Tyrone/West St Pete. Good middle market. Some wholesale opportunities.'),
('Pinellas','St. Petersburg','33712',245000,152,1720,1420,1978,23,2.2,0.96,36,'medium',7.0,'watch','South St Pete inland. More affordable. Know neighborhood specifics.'),
('Pinellas','Clearwater','33756',285000,175,1900,1580,1978,20,1.8,0.97,30,'low',8.5,'secondary','South Clearwater. Reasonable prices. Good retail buyer pool. Secondary for CCG.'),
('Pinellas','Clearwater','33759',268000,164,1820,1510,1978,21,2.0,0.97,32,'low',8.0,'secondary','East Clearwater. Less competitive than core. Some wholesale deals.'),
('Pinellas','Clearwater','33763',295000,178,1950,1620,1978,19,1.8,0.97,28,'low',8.8,'secondary','North Clearwater/Dunedin border. Good market. Dunedin spillover demand.'),
('Pinellas','Dunedin','34698',328000,198,2100,1750,1978,17,1.5,0.98,25,'low',10.2,'secondary','Dunedin. Very desirable market. Craft beer/lifestyle area. Good flip exit but competitive.'),
('Pinellas','Safety Harbor','34695',348000,205,2150,1800,1978,16,1.4,0.98,22,'low',11.0,'secondary','Safety Harbor. Premium small town feel. Strong retail demand. Hard to find deals.'),
('Pinellas','Tarpon Springs','34688',325000,192,2050,1700,1978,18,1.6,0.98,26,'low',9.8,'secondary','Tarpon Springs. Growing market. Greek heritage area. Good flip exit.'),
('Pinellas','Tarpon Springs','34689',298000,180,1950,1620,1978,20,1.8,0.97,29,'medium',8.5,'secondary','Coastal Tarpon. Some flood zone. Interior properties better for investors.'),
('Pinellas','Palm Harbor','34683',365000,212,2200,1840,1978,16,1.4,0.98,20,'low',11.5,'secondary','Palm Harbor. Top school district. Strong retail demand. Premium market.'),
('Pinellas','Palm Harbor','34684',342000,200,2100,1750,1978,17,1.5,0.98,22,'low',10.8,'secondary','East Palm Harbor. Good market. Slightly more accessible than 34683.'),
('Pinellas','Oldsmar','34677',335000,198,2100,1750,1978,17,1.6,0.98,24,'low',10.5,'secondary','Oldsmar. Good retail buyer market. Between Clearwater and Tampa. Strong demand.'),
('Pinellas','Kenneth City','33709',245000,150,1700,1400,1978,22,2.1,0.96,34,'low',7.5,'secondary','Kenneth City. More affordable Pinellas. Some investor opportunity.'),
('Pinellas','Pinellas Park','34665',252000,155,1730,1430,1978,22,2.1,0.96,33,'low',7.8,'secondary','North Pinellas Park. Affordable. Some deals available.'),
('Pinellas','Seminole','33776',305000,184,1980,1640,1978,19,1.7,0.97,27,'low',9.5,'secondary','South Seminole. Good market near beaches. Decent flip territory.'),
('Pinellas','Largo','34640',268000,163,1800,1490,1978,21,1.9,0.97,32,'low',8.2,'secondary','North Largo. More affordable. Some deals possible.'),
('Pinellas','Largo','34641',255000,156,1750,1450,1978,22,2.1,0.96,33,'low',7.8,'secondary','East Largo. Inland. Less competition. Worth monitoring.'),

-- ── ADDITIONAL MARKET AREAS — POLK EXPANDED ─────────────────
('Polk','Lakeland','33801',225000,132,1580,1300,1950,24,2.3,0.96,36,'low',7.5,'secondary','Core downtown Lakeland. Older stock. Some deals come through.'),
('Polk','Lakeland','33803',238000,140,1640,1350,1950,23,2.2,0.96,34,'low',7.8,'secondary','South Lakeland. Established neighborhood. Better deals than downtown core.'),
('Polk','Lakeland','33809',258000,148,1700,1400,1950,22,2.1,0.96,33,'low',8.2,'secondary','North Lakeland. I-4 corridor. Growing area. Some wholesale deals available.'),
('Polk','Lakeland','33811',268000,153,1740,1440,1950,21,2.0,0.97,32,'low',8.5,'secondary','Southwest Lakeland. Good growth area. Better than core Lakeland for investors.'),
('Polk','Lakeland','33812',278000,158,1790,1480,1950,20,1.9,0.97,30,'low',9.0,'secondary','Southeast Lakeland. Stronger end of Lakeland market.'),
('Polk','Winter Haven','33881',222000,130,1560,1280,1950,25,2.4,0.95,36,'low',7.0,'secondary','North Winter Haven. Chain of Lakes area. Different market dynamic.'),
('Polk','Winter Haven','33884',235000,138,1620,1330,1950,24,2.3,0.96,34,'low',7.5,'secondary','South Winter Haven. Better end of WH market.'),
('Polk','Haines City','33844',218000,128,1540,1260,1950,26,2.5,0.95,38,'low',6.5,'watch','Haines City. More rural. Less liquid. Some deals but harder exit.'),
('Polk','Davenport','33837',275000,155,1800,1480,1950,21,2.0,0.97,30,'low',9.0,'watch','Davenport. Vacation rental market. Different buyer profile. Know your exit before buying.'),
('Polk','Auburndale','33823',232000,135,1600,1310,1950,24,2.3,0.96,35,'low',7.2,'secondary','Auburndale. Between Lakeland and Winter Haven. Underserved. Some good deals.'),
('Polk','Bartow','33830',215000,127,1520,1250,1950,26,2.5,0.95,38,'low',6.5,'watch','County seat. More rural feel. Slower market. Only sharp deals.'),
('Polk','Plant City','33563',275000,148,1780,1460,2533,23,2.2,0.96,33,'low',8.0,'secondary','Old Plant City. Historic downtown. Growing. Better than east zips.'),

-- ── ADDITIONAL MARKET AREAS — MANATEE/SARASOTA ───────────────
('Manatee','Bradenton','34205',275000,162,1850,1530,3100,20,1.8,0.97,30,'medium',8.5,'watch','South Bradenton. Some investor opportunity but outside CCG primary territory.'),
('Manatee','Bradenton','34208',298000,172,1950,1610,3100,19,1.7,0.97,28,'low',9.0,'watch','East Bradenton. Better market. Less investor saturation. Secondary consideration.'),
('Manatee','Bradenton','34209',312000,180,2000,1660,3100,18,1.6,0.98,26,'low',9.5,'watch','West Bradenton. Good market. Premium exit for right properties.'),
('Manatee','Palmetto','34221',265000,158,1800,1490,3100,21,2.0,0.97,32,'medium',7.8,'watch','Palmetto. US-41 corridor. Some deal activity. Secondary market.'),
('Manatee','Ellenton','34222',278000,163,1850,1530,3100,21,2.0,0.97,30,'low',8.2,'watch','Ellenton. Growing area near Bradenton. Worth monitoring.'),
('Sarasota','Sarasota','34231',385000,222,2300,1920,3100,17,1.5,0.98,22,'low',11.5,'watch','South Sarasota. Premium market. High prices make CCG criteria very hard to hit.'),
('Sarasota','Sarasota','34232',348000,202,2150,1790,3100,18,1.6,0.98,25,'low',10.5,'watch','East Sarasota. More affordable end of Sarasota. Some deals possible for strong investors.'),
('Sarasota','Sarasota','34233',362000,210,2200,1830,3100,17,1.5,0.98,23,'low',11.0,'watch','Southeast Sarasota. Good schools. Premium retail buyer pool.'),
('Sarasota','Venice','34285',395000,225,2300,1920,3100,16,1.4,0.98,20,'low',12.0,'watch','Venice. Retiree market. Different dynamic. Strong retail demand but high prices.'),
('Sarasota','North Port','34286',285000,162,1880,1560,3100,22,2.0,0.97,28,'low',8.5,'watch','North Port. Fastest growing city in FL some years. Some investor opportunity.'),
('Sarasota','North Port','34288',295000,167,1920,1590,3100,21,1.9,0.97,26,'low',9.0,'watch','East North Port. Growing. Some good deals from motivated sellers.'),

-- ── ADDITIONAL MARKET AREAS — OSCEOLA/ADJACENT ───────────────
('Osceola','Kissimmee','34741',298000,162,1920,1590,2050,21,2.0,0.97,30,'high',8.5,'watch','Kissimmee urban core. High investor activity from vacation rental buyers. Different market.'),
('Osceola','Kissimmee','34743',275000,153,1820,1510,2050,22,2.1,0.96,33,'high',7.8,'watch','East Kissimmee. More residential. Less vacation rental. Some deals possible.'),
('Osceola','St. Cloud','34769',312000,170,2000,1660,2050,20,1.9,0.97,28,'medium',9.0,'watch','St. Cloud. Growing market. Good retail buyer pool. Consider as expansion area.'),

-- ── ADDITIONAL REHAB COST ITEMS ──────────────────────────────
('Attic/Insulation','Attic Insulation Upgrade to R-38','replacement','per_home',1500,3000,5000,'Florida attics reach 150°F+ in summer. Proper insulation critical for HVAC efficiency and buyer appeal. Blown-in insulation typical. Must have proper soffit ventilation.','Damaged batt insulation from prior work','5','Thin or no insulation visible from attic hatch, high utility bills reported by sellers','Insulation directly affects HVAC runtime and buyer utility costs. Good marketing point for energy efficiency.'),
('Attic/Insulation','Air Sealing Package','repair','per_home',800,1800,3500,'Seal all penetrations: light fixtures, HVAC boots, plumbing penetrations. Often overlooked but significant energy impact.','Labor intensive to do properly','10','Drafts, high utility bills, comfort complaints','Pair with insulation upgrade for maximum benefit.'),
('Garage','Garage Door Replacement','replacement','each',1200,1900,3500,'Steel single: $1,200-1,800. Steel double: $1,800-2,800. Insulated double: $2,200-3,500. Impact-rated adds 20-30%.','Track replacement if damaged','5','Dented, off-track, non-functional, manual only','Garage door is high-visibility. Counts in curb appeal immediately.'),
('Garage','Garage Door Opener','replacement','each',350,500,900,'Belt drive preferred for quiet operation. Include keypad and remotes. Smart/wifi opener adds $100-200.','Wiring issues in older homes','5','No opener, broken spring (replace door and opener together)','Budget $500 per garage opener installed. Always include on flips.'),
('Garage','Garage Floor Coating','full','per_home',1500,2800,5000,'Epoxy coating for garage floor. Transforms appearance. Popular with buyers. 1-2 day install.','Floor cracks, moisture issues','10','Oil stains, cracked bare concrete','High ROI for the cost. $2,500 epoxy floor dramatically upgrades garage perception.'),
('Exterior','Stucco Repair and Paint','repair','per_home',2000,5000,12000,'Florida stucco is common on CBS homes. Cracks allow water intrusion — must seal. Elastomeric paint required over stucco. Full repaint over stucco: $4,000-8,000 per home.','Hidden water damage behind stucco cracks','25','Stucco cracks, efflorescence (white staining), delamination, soft spots when pressed','Never skip stucco cracks. Water intrusion creates mold and structural damage quickly in Florida humidity.'),
('Exterior','Pressure Washing','repair','per_home',250,500,1000,'Driveway, walkway, pool deck, exterior walls, screens. Often transforms curb appeal dramatically. Should be done before listing always.','None significant','0','Algae/mold growth on surfaces, dirty driveway/walkways','Always include pressure wash. Cost is minimal, impact is substantial.'),
('Exterior','Soffit and Fascia Repair','repair','per_home',800,2500,8000,'Common failure point in Florida from moisture and pests. Wood soffit/fascia rots. Vinyl or aluminum replacement preferred. Often needed when reroofing.','Rotted wood extent often larger than visible','30','Peeling paint, soft spots, holes, bird/insect damage','Always inspect soffit/fascia closely on any roof job. Often overlooked until bird nests appear.'),
('Exterior','Gutters and Downspouts','replacement','per_home',1200,2000,4000,'Seamless aluminum gutters with downspouts. 6" K-style preferred for Florida rainfall. Gutter guards add $1,000-2,500.','Underground drainage issues at downspout exit','5','Pulling away from fascia, pooling water near foundation','Florida rainfall is intense. Proper guttering protects foundation. Include on any flip.'),
('Exterior','Fence Installation','full','per_home',3000,5500,12000,'Wood privacy (6ft): $25-35/lf installed. Vinyl privacy: $30-45/lf. Aluminum: $25-40/lf. Chain link: $15-25/lf. Corner lots need more fencing.','Property line disputes during install','10','No fence on corner lot where buyers expect it, damaged existing fence','Privacy fence adds value on right properties. Check if neighborhood has fence restrictions.'),
('Exterior','Fence Repair','repair','per_home',500,1500,4000,'Repair or replace sections. Post replacement $150-300/post. Panel replacement $40-80/panel.','Extensive root damage requiring full replacement','20','Leaning posts, rotted wood, broken panels, gates not functioning','Budget $1,000 fence repairs on any property with existing fence.'),
('Exterior','Driveway Resurfacing','repair','per_home',1500,3000,6000,'Asphalt seal coat: $500-1,000. Asphalt overlay: $2,000-4,000. Concrete: $4,000-8,000. Pavers: $8,000-15,000.','Extensive cracking requiring full removal','15','Major cracking, heaving, large holes, severe discoloration','Cracked driveway kills curb appeal. Sealcoat minimum; replace if structural failure.'),
('Pool','Pool Resurfacing','full','per_home',4500,8000,14000,'Plaster: $4,500-7,000. Quartz (PebbleTec): $8,000-12,000. Tile: $12,000-16,000. Florida pools resurface every 10-15 years.','Structural cracks during gunite','20','Rough surfaces, calcium deposits, staining, plaster failure','Pool resurfacing dramatically improves appearance and function. Budget for it on older pools.'),
('Pool','Pool Equipment Replacement','replacement','per_home',2000,4500,9000,'Pump: $800-1,500. Filter: $500-1,000. Heater: $2,000-4,000. Salt system: $1,200-2,000. Variable speed pump: $1,200-2,000.','Underground plumbing leaks','20','Non-functioning equipment, single-speed pump (inefficient), missing heater','Variable speed pump required by code in FL. If replacing any equipment, assess all at same time.'),
('Pool','Screen Enclosure Repair','repair','per_home',800,2500,8000,'Screen replacement: $0.60-1.00/sqft. Structural repair: $100-300/panel. Full rescreening typical: $2,000-5,000.','Structural frame damage requiring replacement','15','Holes, tears, green algae on screens, bowed frames','Budget screen repair on any pool home. Buyers notice immediately.'),
('Pool','Pool Safety Fence','replacement','per_home',1200,2000,4000,'Required by FL law when pool present and child under 6 in household. Code requires pool barrier when selling.','None significant','5','No pool barrier on older homes','FL law 515.27: pool must have barrier. Required disclosure item. Install before listing.'),
('Security','Security System Rough-In','replacement','per_home',500,1200,2500,'Pre-wire for cameras, door/window sensors, panel location. Buyers install their own system on smart home prep.','None significant','5','No security rough-in','Smart home prep is low cost, high perceived value. Add to any $350K+ flip.'),
('SmartHome','Smart Home Package','replacement','per_home',800,1800,3500,'Nest/Ecobee thermostat ($250), smart locks ($200-400/door), video doorbell ($200-400), basic smart lighting. Appeals to tech-savvy buyers.','None significant','5','No smart home features','Budget $1,500 smart home package on $350K+ flips. High perceived value relative to cost.'),
('Water','Water Softener System','replacement','per_home',800,1500,3000,'Florida hard water is very common, especially Pasco and Hillsborough. Causes appliance damage, spots on fixtures. Buyers increasingly expect this in certain areas.','Softener brine tank placement, drainage requirements','5','Hard water staining on fixtures, scale on appliances','Consider on Pasco/east Hillsborough flips where water is hardest. Buyers from Northeast expect soft water.'),
('Water','Water Treatment/Filtration','replacement','per_home',400,900,2500,'Reverse osmosis under sink: $400-800. Whole house filter: $500-1,500. Important in areas with well water or water quality concerns.','None significant','5','Yellow/brown water, strong chlorine smell, sulfur (rotten egg) smell','In Spring Hill/Hernando with well water: include water treatment in scope always.'),
('HVAC','UV Air Purifier (In-Duct)','replacement','per_home',400,700,1200,'UV light kills mold and bacteria in HVAC. Post-COVID buyers increasingly want air quality features. Easy install in air handler.','None significant','5','Musty smell from vents, mold history in home','Low cost, high marketing value. Include in $350K+ flip scope.'),
('Electrical','EV Charging Prep (240V Outlet)','replacement','per_home',800,1400,2500,'Install 240V/50A outlet in garage for EV charging. Increasingly expected by buyers. Especially in Wesley Chapel/New Tampa.','Panel capacity must support','10','No 240V garage outlet','Budget $1,200 EV prep on any 2024+ flip. Buyer expectation shifting quickly.'),
('Electrical','LED Lighting Package','replacement','per_home',600,1200,2500,'All LED fixtures throughout. Recessed lighting in kitchen, living. Ceiling fans in bedrooms. Modern light bars in baths. Buyers notice immediately.','Dimmers incompatible with some LEDs','5','Fluorescent kitchen lights, outdated ceiling fans, brass/bronze fixtures','Modern lighting completely transforms interior perception. Always include.'),
('Kitchen','Kitchen Cabinet Painting','repair','per_home',2500,4500,8000,'Paint and refinish existing cabinet boxes and replace doors/hardware. Cost-effective alternative to full replacement when boxes are solid. Popular technique for budget flips.','Cabinet boxes must be structurally sound','15','Cabinet boxes damaged, particle board swelling, soft spots in boxes','Cabinet painting works when boxes are solid. Inspect carefully before committing.'),
('Kitchen','Quartz Countertop Install','replacement','per_home',3000,5500,9000,'Quartz (engineered stone) is the current buyer expectation for $350K+ flips. Granite also acceptable. Laminate hurts perceived value significantly in that price range.','Unsupported spans, undermount sink weight','10','Laminate countertops in $350K+ market, damaged/dated tile counters','Quartz countertops are table stakes. Never skip on $350K+ flip.'),
('Bathrooms','Shower Glass Door/Enclosure','replacement','per_home',800,1600,3500,'Frameless glass preferred. Shower curtain is a buyer negative. Sliding glass doors acceptable budget option.','Level and square shower required','10','Shower curtain only, plastic shower doors, damaged enclosure','Frameless shower glass is a high-impact, moderate-cost upgrade buyers notice.'),
('Bathrooms','Tile Shower Regrout/Recaulk','repair','per_home',400,900,2000,'Regrout deteriorated tile joints. Recaulk all corners and transitions. Can dramatically extend life of existing tile.','Substrate damage behind tile','15','Black/missing grout, mold in grout lines, failed caulk at tub/wall joint','Often overlooked. $800 regrout can eliminate need for full bath gut.'),
('Flooring','Tile Removal and Prep','repair','per_home',1000,2500,5000,'Remove existing tile to bare concrete, prep for new flooring. More expensive than install over but often necessary for quality result.','Damaged slab revealed after removal','20','Cracked tile throughout, height transition issues, loose tile','Budget tile removal separately when planning LVP over old tile. Height and adhesive residue matter.'),
('Landscaping','Sod Installation','full','sqft',0.65,0.95,1.50,'St. Augustine sod is standard for Florida flips. Install over prepared soil. Must include irrigation or immediate watering. Bahia is cheaper but lower quality appearance.','Irrigation system adequacy','10','Dead lawn, dirt patches, weeds throughout','Budget St. Augustine sod for any flip where yard is dead. $2,500-6,000 typical for average lot.'),
('Landscaping','Irrigation System Repair','repair','per_home',500,1500,4000,'Broken heads, controller replacement, zone repair. Full install if no irrigation: $3,000-6,000. Many FL homes require irrigation to maintain landscaping.','Underground line damage, pump issues','20','No irrigation system on larger lot, broken heads visible, dry zones','In FL heat, landscaping dies without irrigation. Budget irrigation repair if any scope changes required.'),
('Landscaping','Tree Removal','repair','per_home',500,2000,8000,'Small tree $300-600. Medium $800-1,500. Large $1,500-4,000. Emergency removal (after storm) much higher. Stump grinding: $100-300 per stump.','Root damage to utilities','10','Dead trees, trees touching house/roof, large overhanging branches','FL homeowners insurance may require tree removal near structure. Always inspect.'),
('Miscellaneous','Interior Door Replacement','replacement','per_home',1500,3000,6000,'Hollow core doors throughout. 6-panel colonial is standard. Replace all interior doors on full gut. Install 2-inch door casings. Prehung doors including hardware: $250-400 each.','Non-standard opening sizes','10','Hollow core doors damaged, mismatched doors throughout','Budget $3,000 interior doors and hardware on full gut. High visual impact.'),
('Miscellaneous','Bathroom Mirrors and Accessories','replacement','per_home',400,800,1500,'Frameless mirrors or framed mirrors to match vanity. Towel bars, toilet paper holder, robe hooks per bath. Chrome or brushed nickel to match fixtures.','None significant','5','Missing or dated accessories, builder-grade plastic accessories','$600 in bath accessories and mirrors completes the bathroom without much spend.'),
('Miscellaneous','Mailbox and House Numbers','repair','per_home',100,250,600,'New mailbox ($60-150), house numbers visible from street ($20-80), address stone if neighborhood standard.','HOA requirements on mailbox style','5','No mailbox, damaged mailbox, house numbers not visible','$200 for new mailbox and house numbers. Inspectors and appraisers note address visibility.'),
('Miscellaneous','Radon Mitigation','repair','per_home',800,1200,2500,'Less common in FL than northern states but exists in some areas, especially inland. If testing reveals elevated levels, mitigation system required. Usually 1-day install.','Slab penetration in finished spaces','5','Elevated radon test results (>4 pCi/L)','Test if buyer requests or if property is inland elevated terrain. Budget $1,200 if mitigation needed.');


-- ── MASSIVE MARKET KNOWLEDGE EXPANSION ───────────────────────
INSERT INTO market_knowledge (topic, category, subcategory, content, key_numbers, action_implications, source, confidence, applies_to_counties, applies_to_deal_types, tags) VALUES

-- LEGAL / PROCESS
('Florida Foreclosure Process','legal','foreclosure','Florida is a judicial foreclosure state — foreclosures go through court. Timeline typically 180-365 days from filing. Process: lis pendens filed → summons served → answer period (20-35 days) → motion for summary judgment → foreclosure sale scheduled → clerk sale → certificate of title issued. Pre-foreclosure (lis pendens stage) is where investors can approach distressed sellers directly for off-market deals.','Timeline: 6-18 months from lis pendens to sale. Lis pendens: public record filed at courthouse day 1.','Monitor lis pendens filings at county clerk websites. Approach sellers in pre-foreclosure — they often prefer selling directly over losing to bank. Best outreach: early in the process (30-60 days after filing).','Florida Statutes 702','high',NULL,ARRAY['flip','wholesale','brrrr'],ARRAY['legal','foreclosure','florida','off_market']),

('Florida Tax Deed Sale Process','legal','tax_deed','When property taxes are unpaid, county sells a tax certificate at auction. After 2+ years of delinquency, certificate holder can apply for tax deed. Tax deed sale happens at county courthouse (now online in most FL counties). Winning bidder gets deed — prior liens typically extinguished EXCEPT federal liens and HOA liens.','Tax delinquency starts: April 1 each year. Certificate sold: June auction. Tax deed application: 2+ years after cert purchase. Clearance of liens: most except fed/HOA.','Monitor tax deed auction calendars at county property appraiser and tax collector websites. Research properties before bidding — no inspection rights and condition unknown. Better for experienced investors.','Florida Statute 197','high',NULL,ARRAY['wholesale','flip'],ARRAY['legal','tax_deed','auction','off_market']),

('Florida Probate Process for Real Estate','legal','probate','When a property owner dies, their estate goes through probate before heirs can sell. Florida probate: Personal Representative (PR) appointed → inventory filed → creditors notified (90-day window) → final accounting → distribution. PR has authority to sell property with court approval. Timeline: 6 months minimum for simple estates, 12-18 months for complex.','Simple probate: 6-9 months. Complex: 12-24 months. Testate (will): faster. Intestate (no will): longer. PR fee: 3% of estate value.','Network with probate attorneys. Heirs often want to sell quickly to distribute funds. PR must price at or near market value with court oversight. Best approach: respectful outreach directly to PR or heirs offering clean cash close.','Florida Probate Code','high',NULL,ARRAY['flip','brrrr','wholesale'],ARRAY['legal','probate','off_market','estate']),

('Florida Eviction Process (Landlord Rights)','legal','tenant_law','Florida eviction timeline: Serve written notice (3-day for non-payment, 7-day for lease violations, 15-day for month-to-month) → file eviction (if no compliance) → serve summons → tenant has 5 days to respond → default judgment or hearing → writ of possession → sheriff enforces (24-48 hours notice). Total minimum timeline: 2-4 weeks if uncontested. With tenant fighting: 2-3 months.','3-day notice for non-payment (must be exact amount owed, no grace period). Filing fee: ~$185-200. Writ of possession: $90-95 plus sheriff service. Budget $500-800 total if uncontested.','Factor eviction costs and timeline into tenant-occupied deals. Get an estoppel letter from all tenants. Consider cash-for-keys ($500-2,000) instead of eviction — much faster and less hassle. Hernando and Pasco courts faster than Hillsborough.','Florida Statute 83','high',ARRAY['Hillsborough','Pasco','Hernando','Pinellas','Polk'],ARRAY['rental','brrrr'],ARRAY['legal','eviction','tenant','landlord']),

('Florida Landlord-Tenant Law Basics','legal','tenant_law','FL Statute 83 governs landlord-tenant relationships. Key rules: Security deposit: must be held in separate account or posted surety bond. Return within 15 days (no deductions) or 30 days (with itemized deductions). Landlord entry: 12-hour notice required except emergency. Required disclosures: radon, lead paint (pre-1978), HOA rules, fire safety (3+ units). Rent increases: no statewide control — landlord can increase with proper notice.','Security deposit: return within 15 days or 30 with itemized list. Notice to enter: 12 hours. Month-to-month termination: 15 days notice by either party.','Use proper FL lease agreement (Florida Realtors forms or attorney-drafted). Always do thorough tenant screening. Document property condition with photos at move-in and move-out. Keep security deposit in separate account.','Florida Statute 83','high',NULL,ARRAY['rental','brrrr'],ARRAY['legal','landlord','tenant','florida']),

('Section 8 / HCV in Tampa Bay','legal','rental','Housing Choice Voucher (Section 8) program provides rental assistance to low-income tenants. Administered by Tampa Housing Authority and Hillsborough County. Landlords receive guaranteed payment from housing authority (portion or all of rent). Rent must be at or below Fair Market Rent (FMR). Property must pass HQS inspection before tenant moves in. Tampa Bay HCV wait lists are very long — Section 8 tenants are stable once placed.','HQS inspection: landlord must address any deficiencies. Payment: direct from housing authority to landlord. HCV market rents: tied to HUD FMR. Tampa Housing Authority: (813) 253-0551.','Consider accepting Section 8 on rentals in B/C class neighborhoods — guaranteed government check, stable tenancy. Property must be well-maintained to pass inspection. Good for Spring Hill, older Tampa zips.','HUD, Tampa Housing Authority','high',ARRAY['Hillsborough','Pasco','Hernando'],ARRAY['rental','brrrr'],ARRAY['section_8','hcv','rental','tenant']),

('Seller Financing Structures','legal','creative_finance','In a seller-financed deal, the seller acts as the bank. Common structures: 1) Land contract/contract for deed (seller retains title until paid), 2) Purchase money mortgage (buyer gets title, seller holds note/mortgage), 3) Wrap mortgage (seller has existing mortgage, wraps a new note). CCG might offer seller financing to motivated sellers who need installment income rather than lump sum.','Typical seller finance: 5-8% interest rate, 5-30 year term, 10-20% down. Monthly payment to seller. Closing simpler than conventional.','Use seller financing as a tool when: seller has no mortgage, seller needs income rather than lump sum, seller is in estate/probate situation, seller is avoiding capital gains. Offer monthly income story vs lump sum tax event.','Real estate finance principles','high',NULL,ARRAY['flip','brrrr','rental'],ARRAY['creative_finance','seller_financing','structure']),

('Subject-To Purchase Strategy','legal','creative_finance','Buying a property subject to the existing mortgage means you take title while the seller''s mortgage stays in their name. You make the seller''s mortgage payments. Risk: due-on-sale clause — lender can call loan due. In practice, lenders rarely enforce if payments are current. Used when: seller has equity problem (can''t sell for enough to pay realtor), seller needs quick exit, seller has good interest rate.','Due-on-sale clause in virtually all mortgages. But lenders rarely enforce when payments current. CCG note: consult attorney before doing subject-to deals. Not a standard part of CCG current model but worth understanding.','Subject-to is advanced strategy. Not primary CCG approach but valuable to understand when evaluating creative deal structures or unusual wholesaler offers.','Real estate investing','medium',NULL,ARRAY['flip','brrrr'],ARRAY['creative_finance','subject_to','structure']),

('1031 Exchange for CCG Exits','legal','tax','A 1031 like-kind exchange allows deferring capital gains taxes when selling investment property by reinvesting proceeds into another investment property. Rules: 45 days to identify replacement, 180 days to close, must use qualified intermediary (QI). Cannot be primary residence or property held for resale (flips typically don''t qualify — rentals do).','45-day identification window. 180-day close window. Must use QI from day 1 of sale. Cannot touch sale proceeds (must go directly to QI).','Relevant for Caleb''s rental/BRRRR properties when selling. NOT applicable to flips (held for resale = dealer property). Use 1031 on any rental held 12+ months being sold to trade up or consolidate portfolio.','IRS Revenue Ruling 2004-86','high',NULL,ARRAY['rental','brrrr'],ARRAY['tax','1031','exchange','capital_gains']),

('Capital Gains Tax on Flips','legal','tax','Flip profits are taxed as ordinary income (not capital gains) because properties held for resale are considered inventory/dealer property. Short-term capital gains rate applies if held <12 months. Tax rate depends on income level — typically 22-37% for active real estate investors. Self-employment tax also applies on flip income if in business of flipping. Proper entity structure (S-corp) can reduce SE tax burden.','Ordinary income rates: 22-37% depending on income. SE tax: 15.3% on self-employment income (reduced if S-corp). State income tax: FL has no state income tax — major advantage.','Work with a CPA experienced in real estate. Consider S-corp election for business if doing volume. Keep meticulous records of all costs (acquisition, rehab, holding, selling) to maximize basis.','IRS Pub 544','high',NULL,ARRAY['flip','wholesale'],ARRAY['tax','capital_gains','flips','income_tax']),

('Florida No State Income Tax Advantage','legal','tax','Florida has no personal state income tax. Significant advantage vs states like California (13.3%), New York (10.9%), Georgia (5.75%). For investors moving from those states, this is a major financial benefit. Also no corporate income tax on most small entities. Property tax and documentary stamp tax remain.','FL state income tax: 0%. Avg savings vs California: 9-13% of income. For $500K income, saves $45,000-65,000 vs CA.','Use FL no-income-tax advantage in conversations with out-of-state investors considering FL rental/BRRRR investments. Strong marketing point for direct mail to out-of-state landlords.','Florida DOR','high',NULL,ARRAY['rental','brrrr'],ARRAY['tax','florida','advantage','no_income_tax']),

-- MARKET DYNAMICS
('Tampa Bay Population Growth Drivers','market_dynamics','macro','Tampa Bay MSA is one of the fastest-growing in the US. Growth drivers: retirees from Northeast (NY, NJ, MA, CT), remote workers relocating for cost of living, corporate relocations (Hologic, PricewaterhouseCoopers, Goldman Sachs), military (MacDill AFB), healthcare and university employment (USF, HCC). Population growth sustains housing demand and rental demand.','Tampa MSA population: ~3.2M. Annual growth: ~50,000 new residents. MacDill AFB: 16,000+ military. USF: 50,000+ students.','Sustained demand fundamentals support continued investment. Even in market slowdowns, fundamentals are strong. Different from speculative markets.','US Census, Tampa Bay Partnership','high',ARRAY['Hillsborough','Pasco','Hernando','Pinellas','Polk'],ARRAY['flip','rental','brrrr','wholesale'],ARRAY['market','growth','population','fundamentals']),

('iBuyer Impact on Tampa Bay Market','market_dynamics','competition','iBuyers (Opendoor, Offerpad, Zillow Offers - now shut down) significantly impacted wholesale deal flow in 2021-2022. They aggressively paid near-market prices for properties that previously went to wholesalers. Post-2022, iBuyers retreated significantly. Opendoor and Offerpad remain active but much more conservative pricing. This has somewhat restored traditional wholesale channels.','Opendoor active in Tampa: makes offers within 24 hours. Typically pays 93-97% of market with fees. Still competes for some deals.','Be aware iBuyers are an option sellers know about. When wholesalers say "seller has another offer," sometimes it is an iBuyer. If deal economics work, compete on speed and certainty. iBuyers have 60-day close — CCG can close in 7-14 days.','Market observation','high',ARRAY['Hillsborough','Pasco','Hernando','Pinellas'],ARRAY['flip','wholesale'],ARRAY['ibuyer','competition','market','opendoor']),

('New Construction Competition in Target Markets','market_dynamics','competition','New construction significantly impacts resale flip values in rapidly growing areas. Wesley Chapel and Land O Lakes have massive new construction. KB Home, DR Horton, Lennar, Pulte all active. New construction prices $290K-$450K+ compete directly with renovated flips. Buyers get warranties, energy efficiency, customization. This creates pricing ceiling pressure in new-construction-heavy areas.','New construction delivery timeline: 6-12 months. Builder incentives: 5-7% of purchase price common. Buyer preference: ~40% prefer new vs resale.','In new construction heavy areas (Wesley Chapel, Land O Lakes new sections), renovated flips must be priced 5-10% below comparable new construction to move. In established neighborhoods, less competition. Target areas with limited new construction supply.','Local builder activity monitoring','high',ARRAY['Pasco','Hillsborough'],ARRAY['flip'],ARRAY['new_construction','competition','pricing','market']),

('Out-of-State Investor Activity in Tampa Bay','market_dynamics','competition','Tampa Bay attracts significant out-of-state investor capital. California investors escaping high prices and taxes. New York/New Jersey investors seeking higher yields. Sun Belt migration capital. These investors drive competition and compress cap rates on rentals. Also creates exit market for flips sold to investor buyers.','Out-of-state investors: estimated 30-40% of investor purchases in Tampa MSA. Cap rate compression: 5-7% gross cap common where 8-10% was normal pre-2021.','Target C-class and B-minus neighborhoods that large out-of-state capital ignores. Focus on sub-$300K acquisition price range. Build direct relationships with local end buyers who outcompete out-of-state on knowledge.','Market observation, ATTOM data','high',ARRAY['Hillsborough','Pasco','Pinellas'],ARRAY['flip','rental','brrrr','wholesale'],ARRAY['competition','out_of_state','investors','cap_rates']),

('Tampa Bay Rental Market Fundamentals','market_dynamics','rental','Tampa Bay rental market remains strong despite increased supply from new apartments. Single family rental (SFR) demand significantly outpaces supply. Vacancy rates: SFR typically 4-6%, apartments higher (8-12%). Rental growth has slowed from 20%+ in 2021-2022 to 3-7% annually in 2024. SFR preferred by families due to schools, yards, garages. Strong military and healthcare worker tenant base.','SFR vacancy: ~5%. Monthly rent growth YoY: 3-7% (slowed from 20%+ peak). Tenant profile: family renters, military, healthcare workers, USF students (east Tampa).','SFR rentals remain the best risk-adjusted hold in Tampa Bay. Focus on school zone quality — drives tenant demand and retention. Long-term hold thesis remains strong. BRRRR viable in most primary markets.','Tampa Bay market research','high',ARRAY['Hillsborough','Pasco','Hernando','Pinellas'],ARRAY['rental','brrrr'],ARRAY['rental_market','fundamentals','vacancy','demand']),

('Deal Flow Seasonality in Tampa Bay','market_dynamics','seasonality','Wholesale deal flow in Tampa Bay follows seasonal patterns. Peak: January-April (snowbirds selling, estate liquidations, tax pressure, new year motivation). Summer (June-August): slowest for wholesale volume, investors leave for vacations. Fall (September-November): strong second season, motivated sellers before holiday season. December: very slow. Holiday weeks: nearly dead.','Peak months: Jan-April. Slowest: December, July-August. Best deals historically come through: January and February (motivated sellers from holidays).','Adjust outreach and acquisition goals seasonally. Be MORE aggressive Jan-April. Can be more selective June-August. Plan slower months for systems improvement, relationship building, property evaluations. Staff appropriately.','CCG operational history','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['seasonality','deal_flow','strategy']),

('Cash Buyer Profile Analysis','market_dynamics','buyers','Understanding who buys from wholesalers in Tampa Bay. Type A: Active flippers — buy at 70-75% ARV minus repairs, need 14-day close, pay cash. Type B: Landlords/BRRRR — buy at 80-85% ARV if cash flows, some use HML. Type C: Turnkey buyers — pay more for less work needed, often out-of-state. Type D: New investors — often overpay, reliable for moving product at slight discount to market. Type E: Institutional (Invitation Homes, etc.) — very specific criteria, slow but reliable.','Flipper MAO: 70% ARV - repairs. Landlord MAO: where DSCR works. Turnkey premium: 5-10% over flipper price. New investor: sometimes at ARV minus 5%.','Build buyers list with all types. Match deal to right buyer type. A wholesale deal at 65% ARV goes to a flipper. A turn key rental at 80% ARV goes to a landlord/turnkey buyer. Having diverse buyer types maximizes deal options.','Market observation','high',NULL,ARRAY['wholesale'],ARRAY['buyers','cash_buyers','wholesale','deal_matching']),

('Motivated Seller Triggers','market_dynamics','off_market','Understanding why sellers accept below-market prices unlocks off-market deal flow. Major triggers: 1) Foreclosure/financial distress (most common), 2) Inherited property (heirs want cash, not landlording), 3) Divorce (both parties want out fast), 4) Job relocation (must sell, timeline matters), 5) Tax delinquency (selling to avoid lien foreclosure), 6) Landlord fatigue (tired of managing tenants), 7) Probate (estate liquidation), 8) Age/health (downsizing, assisted living needed), 9) Code violations (property is maintenance burden), 10) Out-of-state owner (managing from distance is hard).','Best motivation overlap: inherited + out-of-state + aging = near-perfect motivated seller profile. Direct mail response rates: 0.5-2% (some operators hit 3-5% with great lists and creative).','Train Adam to identify motivation in conversations. Listen for pain points, not just price objections. The solution is solving their problem (fast cash, no repairs, fast close), not necessarily highest price.','Real estate investor knowledge base','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['motivated_sellers','off_market','strategy']),

-- CONSTRUCTION / DUE DILIGENCE
('Foundation Types in Florida','construction','foundations','Florida mostly has slab-on-grade foundations (no basement). Very common due to high water table. Slab issues: cracks (settlement, sinkholes, expansive soil), plumbing under slab (expensive to repair), water intrusion. Some older homes have block/pier foundations (pre-1960s). Rare in FL: full basement (water table too high).','Slab inspection: structural engineer if cracks visible. Slab plumbing repair: $5,000-50,000+ depending on scope. Sinkhole investigation: $2,500-5,000.','Always probe for slab cracks, soft spots, doors/windows that stick (settlement indicator). Get engineering review if any concerns. Slab plumbing leaks are common hidden cost in older FL homes.','FL contractor experience','high',NULL,ARRAY['flip','brrrr','rental'],ARRAY['construction','foundation','slab','florida']),

('Termite Treatment Options Florida','construction','pests','Florida has both drywood and subterranean termites. Drywood: live in wood, smaller colonies, localized treatment possible. Subterranean: live in soil, huge colonies, need perimeter treatment. Options: tent fumigation (drywood, kills everything, 2-3 days out), liquid treatment (subterranean, soil injection), Sentricon bait system (ongoing, green option). Annual WDO inspection recommended.','Tent fumigation: $1,000-3,500 depending on size. Liquid treatment: $800-2,000. Sentricon annual: $300-500/year. Structural damage: highly variable ($2,000-50,000+).','Get WDO (Wood Destroying Organisms) inspection on every deal. Cost: $75-150. If active termites: negotiate treatment into price or walk. If structural damage: get contractor estimate and deduct from offer. Do NOT skip.','FL pest control industry','high',NULL,ARRAY['flip','brrrr','rental'],ARRAY['construction','termites','pests','wdo','inspection']),

('Florida Septic System Facts','construction','plumbing','Approximately 2.6 million FL homes use septic systems. Hernando County: very high prevalence. Rural Pasco: common. Most Tampa core: municipal sewer. Septic components: tank (1,000-1,500 gallon typical), drain field (absorption field). Pump every 3-5 years ($300-500). Failure: drain field saturation is most common ($8,000-20,000 to replace). Seller must disclose known septic issues.','Septic inspection: $250-400. Pumping: $300-500. Drain field replacement: $8,000-20,000. Connecting to sewer if available: $8,000-20,000+ depending on distance.','ALWAYS ask about septic vs sewer on any Hernando County or rural property. Get septic inspection on every deal with septic system. Scope includes: pump, inspect, dye test. Failed drain field can make deal unviable unless discounted appropriately.','FL Dept of Health','high',ARRAY['Hernando','Pasco'],ARRAY['flip','brrrr','rental'],ARRAY['construction','septic','plumbing','hernando']),

('Well Water System Facts Florida','construction','plumbing','Properties on well water common in Hernando, rural Pasco, rural Hillsborough. Well components: well pump ($800-2,000 to replace), pressure tank ($300-600), treatment system (often needed). Water quality issues in FL: hardness (calcium/magnesium), iron (red staining), sulfur (rotten egg smell), tannins (brown color). Well inspection: pump test, flow test, water quality test.','Well pump replacement: $800-2,000. Pressure tank: $300-600. Water treatment system: $400-3,000. Well water test: $100-300.','Test well water on every well property. Testing reveals: bacteria, nitrates, pH, hardness, iron, sulfur. Test results affect property value and buyer financing (some lenders require potable water testing). Budget water treatment in scope if issues found.','FL Dept of Environmental Protection','high',ARRAY['Hernando','Pasco'],ARRAY['flip','brrrr','rental'],ARRAY['construction','well_water','plumbing','hernando']),

('Impact Windows and Doors in Florida','construction','windows','Florida Building Code requires wind-resistant openings in new construction. Older homes may or may not have impact windows. Areas within 1 mile of coast in wind zones B/C/D require impact-rated products. Impact windows/doors: steel-reinforced frame, laminated glass, tested to 110-200+ mph. Benefits: major insurance premium reduction, hurricane protection, noise reduction, no storm shutters needed.','Impact window cost: $400-700/window installed. Full home: $12,000-30,000+. Insurance savings: $1,000-3,000+/year in coastal areas. Wind mitigation credit: significant.','Check wind zone on every deal. Coastal Pinellas and coastal Hillsborough: impact windows may be required for any permitted opening work. Non-coastal: standard windows acceptable but impact windows add value and reduce insurance costs.','FL Building Commission','high',ARRAY['Pinellas','Hillsborough','Pasco'],ARRAY['flip','brrrr','rental'],ARRAY['construction','impact_windows','hurricane','insurance']),

('Skip Tracing Methods for Off-Market Leads','market_dynamics','off_market','Skip tracing finds contact information for property owners who are hard to reach. Methods: 1) BatchLeads/BatchSkipTracing — batch process lists for phone/email, 2) LexisNexis/TLO — comprehensive people search, 3) BeenVerified — consumer-grade skip trace, 4) County property records — look up owner mailing address, 5) Social media — Facebook/LinkedIn for found names. Best for: absentee owners, inherited properties, tax delinquent owners.','BatchSkipTracing: ~$0.12-0.25/record. LexisNexis: ~$0.50-2.00/record (more accurate). Hit rate on mobile numbers: 60-80%. Success rate to contact: 30-50%.','Pair skip tracing with PropStream lists. Pull absentee owner list → skip trace → load into SMS/RVM/direct mail campaign. Adam can manage this entire process.','Real estate investor community','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['skip_tracing','off_market','lead_generation']),

('Direct Mail Campaign Best Practices','market_dynamics','off_market','Direct mail to motivated sellers. Best lists: pre-foreclosure, probate, inherited properties, tax delinquent, absentee owners 10+ years. Caleb has 55K/day capacity. Keys to response rate: targeted list selection > quantity. Personalization matters. Yellow letter (handwritten look) outperforms postcard for motivated sellers. Repeat touches: need 5-7 touches average before response. Track by campaign, list type, zip.','Industry average response rate: 0.5-2%. Cost per lead: $30-100 depending on list and send volume. Cost per deal at scale: $1,000-5,000. 55K mailers/day = massive scale advantage.','CCG has significant direct mail infrastructure advantage with 55K/day capability. Use this systematically. Build campaigns targeting probate, pre-foreclosure, and long-term absentee by county. Track everything by campaign code.','Direct mail industry data','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['direct_mail','off_market','lead_generation','marketing']),

('PropStream Intelligence for Tampa Bay','market_dynamics','off_market','PropStream provides comprehensive property data: owner info, mortgage data, equity estimates, MLS history, tax data, foreclosure status, and list-building capabilities. Most valuable lists for CCG: Pre-foreclosure (lis pendens filed), High equity absentee owners (50%+ equity, not living there), Tax delinquent (delinquent 1+ years), Inherited properties (ownership change with death indicator), Out-of-state absentee (mailing address >50 miles from property).','PropStream cost: ~$99/month. List export: 100 records/month included. Additional records: fee. Mobile numbers available via skip trace integration.','Build saved searches in PropStream for each target county with criteria: SFR/duplex, 1975-2005 build, 1,000-2,500 sqft, absentee owner. Pull monthly and add to outreach pipeline.','PropStream platform','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['propstream','data','off_market','list_building']),

('Driving for Dollars App Strategy','market_dynamics','off_market','Driving for dollars: physically drive neighborhoods looking for distressed properties. Signs of distress: overgrown lawn, tarped roof, boarded windows, peeling paint, structural issues, newspapers piling up, obvious deferred maintenance. Apps: DealMachine (takes photo, gets owner info immediately, sends postcard), BatchLeads, Propstream. Most effective in specific neighborhoods where you know values.','DealMachine cost: $49-99/month. Per lead saved: ~$0.20-0.30 for skip trace. Direct mail from app: ~$0.75-1.50/postcard. Response rates for DFD: 1-3% (targeted).','Good supplemental strategy for specific neighborhoods. Best use: deploy Spring Hill, Zephyrhills, Seffner, and similar target zips. Document distressed properties. Let Scout agent manage driving routes and data capture.','Real estate investor community','medium',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['driving_for_dollars','off_market','dfd','neighborhood']),

('Probate Attorney Network Strategy','market_dynamics','off_market','Building relationships with probate attorneys is a high-value, low-competition lead source. Probate attorneys manage estates that often include real estate. They represent heirs who need property liquidated. Approach: identify probate attorneys in target counties (search Florida Bar website), introduce yourself as a cash buyer who can close quickly, offer to be a referral resource. Some pay referral fees (check FL Bar rules).','FL probate court filings are public record. Probate attorney referral fee: check FL Bar Ethics rules for structure. Timeline: attorney gets case → weeks to months before property listed.','Have Adam monitor Hillsborough, Pasco, Hernando probate court filings weekly. Identify properties. Build template outreach for heirs/PRs. Build attorney relationships through consistent professional outreach. Long-term relationship play.','Real estate investor community','high',ARRAY['Hillsborough','Pasco','Hernando'],ARRAY['flip','brrrr','wholesale'],ARRAY['probate','off_market','attorney','network']),

('Wholesaler Daisy Chain Identification','market_dynamics','wholesalers','A daisy chain occurs when wholesaler B has a deal from wholesaler A, and tries to assign to CCG without disclosing this. Multiple assignment fees get stacked. Signs of daisy chain: wholesaler cannot answer basic property questions, photos look like theirs were taken from another wholesaler email, asking price seems unusually high for area, wholesaler says "I need to check with my partner" constantly, close date is unusually short.','Each assignment fee in a daisy chain: $5,000-20,000. Total markup from original seller: can be 15-25% above what CCG should pay.','Adam should ask upfront on unknown wholesalers: "Are you the original buyer under contract or are you assigning from another party?" This is a professional, normal question. If daisy chain is confirmed: either pass or get a direct deal from the original wholesaler. Rarely worth doing a daisy chain deal.','Wholesaler market observation','high',NULL,ARRAY['wholesale','flip','brrrr'],ARRAY['daisy_chain','wholesalers','due_diligence','negotiation']),

('Wholesaler ARV Inflation Psychology','market_dynamics','wholesalers','Wholesalers systematically inflate ARV to justify their asking price. Reasons: 1) They paid too much for the deal and need more, 2) They don't know the market, 3) They use cherry-picked comps, 4) They are aware of planned updates that raise ARV. Average inflation in Tampa Bay wholesale market: 10-20% above realistic ARV. Some wholesalers consistently inflate 25-30%.','Industry observation: 70% of wholesale deals have ARV inflated by 10%+ vs actual. Top 20% of wholesalers (A-grade) are within 10%. Bottom 20% inflate 25%+ consistently.','Urban AI exists specifically to counter this. Always use Urban ARV vs wholesaler ARV. Note pattern for each wholesaler in database. If consistent inflator, adjust credibility score and negotiate harder from the start.','CCG Urban AI analysis','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['arv_inflation','wholesalers','negotiation','urban_ai']),

('Reading a Title Commitment','legal','title','Title commitment (also called title binder) is issued by title company before closing. Sections: Schedule A (property description, buyer, seller, loan amount), Schedule B-I (requirements to clear before closing — pay off liens, cure defects, get releases), Schedule B-II (exclusions — what title insurance won''t cover). ALWAYS read Schedule B-I carefully — this is what needs to happen before you can close.','Common Schedule B-I items: pay off existing mortgage, pay off liens, satisfy judgments, cure boundary disputes, get HOA estoppel. Common B-II exclusions: survey matters, zoning violations, matters of public record.','Review every title commitment before releasing due diligence. If B-I has complex requirements, assess if they can be cleared before close. Extend due diligence if title issues surface late. Title issues are deal killers — address early.','Title company practice','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['title','closing','legal','due_diligence']),

('Lien Types That Survive Sale','legal','title','Some liens survive a property sale and transfer to new buyer. ALWAYS research: 1) Code enforcement liens (FL — can survive if recorded before you purchase), 2) HOA super liens (FL gives HOAs priority), 3) IRS tax liens (federal, survive), 4) Mechanic''s liens (survive if properly perfected), 5) Environmental liens (survive). DO NOT SURVIVE typically: mortgage liens (paid at closing), judgment liens (paid at closing), property tax liens (paid at closing).','Code enforcement lien: $250-$1,000/day can accrue. HOA lien: typically 12 months of dues with priority. IRS tax lien: must be paid or subordinated. Mechanic lien: 90-day filing window from last date of service.','Always run comprehensive lien search through title company. Check county code enforcement database before offer. Ask wholesaler: "Are you aware of any code violations or open permits?" Recorded liens visible in title search; unrecorded/recent may not appear.','Florida title law','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['liens','title','due_diligence','legal','code_enforcement']),

('Code Enforcement Liens — Critical Warning','legal','code_enforcement','Florida code enforcement liens can be devastating. Municipality can impose fines of $250-1,000/DAY for code violations. These accrue indefinitely. Liens are recorded and run with land — new buyer inherits unless resolved before closing. Common violations: unpermitted additions, overgrown lawn, debris, inoperable vehicles, fence violations, structural issues. Resolution: usually pay the accrued fine (with negotiation possible) OR have municipality forgive after violation corrected.','$250/day for 3 years = $273,750 lien. But most are negotiable — municipalities often settle for 10-20% of accrued amount if violation corrected. Check: city/county code enforcement office, not just title company.','ALWAYS check code enforcement status on every deal before offering. Check the SPECIFIC municipality (some properties have both city AND county jurisdiction). Run county public records AND city directly. Budget $500-5,000 to resolve typical violations.','FL code enforcement law','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['code_enforcement','liens','title','risk','due_diligence']),

-- FINANCING
('Hard Money Draw Process — Detailed','finance','lending','HML draw process for rehab projects: 1) Submit draw request to lender with photos of completed work and contractor invoices, 2) Lender sends inspector within 1-3 business days, 3) Inspector confirms work completion and approves % draw, 4) Funds released in 1-3 more business days. Total draw cycle: 3-7 business days. Plan your rehab cash flow around draw timing — you often pay contractors first, then get reimbursed.','Draw inspection fee: $75-150/draw. Draw processing time: 3-7 days total. Typical draw schedule: 4 draws (foundation/rough, rough-in, drywall, final). Hold-back: 10-20% until final inspection.','Budget cash flow for 7-10 day draw lag. Never let contractors get ahead of draws — they may abandon project if not paid. Always have 1-2 draws worth of cash available as float. Keep meticulous photo documentation of all completed work.','HML industry practice','high',NULL,ARRAY['flip','brrrr'],ARRAY['hml','draws','finance','construction']),

('BRRRR Refinance Timing and Process','finance','brrrr','BRRRR refinance details: 1) Most DSCR lenders require 6-12 months seasoning (time owned) before refinancing. 2) Order appraisal 30 days before desired refi date. 3) Must have tenant in place (DSCR is based on rental income). 4) Lender orders their own appraisal — may differ from your ARV estimate. 5) Process: application → appraisal → underwriting → closing (45-60 days total).','Seasoning requirement: typically 6-12 months. DSCR appraisal: $500-800. Rate lock: 30-60 days. Closing costs on refi: 2-3% of loan amount.','Time rehab to have tenant in place before refinancing. Screen tenants carefully — lender will verify rental income. Get lease signed before starting refi process. Build 3-4 month buffer between rehab complete and refi application.','DSCR lender practice','high',NULL,ARRAY['brrrr'],ARRAY['brrrr','refinance','dscr','finance']),

('Portfolio Loan Strategy','finance','lending','Portfolio loans are kept on the lender''s books rather than sold to Fannie/Freddie. Benefits: can close in LLC/trust name, no conventional loan limits, no 10-loan cap (Fannie), flexible underwriting for investors with many properties. Common portfolio loan terms: 6-8% rate, 20-25 year term, interest only options, cross-collateralization possible.','Conventional loan cap: 10 properties. Portfolio loans: no cap. Typically: 25% down, 6.5-8% rate. Community banks and credit unions most common source.','As CCG scales rental portfolio, conventional loans become unavailable after 10. Portfolio loans are the path to 20, 30, 50+ doors. Start building relationships with portfolio lenders now. Ameris Bank, Seacoast Bank active in Tampa Bay.','Portfolio lending community','high',NULL,ARRAY['rental','brrrr'],ARRAY['portfolio_loans','lending','scale','rentals']),

-- CCG STRATEGY
('CCG Competitive Advantages','ccg_strategy','competitive_position','CCG core competitive advantages in Tampa Bay wholesale market: 1) $20M RLOC — can close in 1-3 days vs competitor 7-14 days. 2) Urban AI — more accurate ARV analysis than gut-feel competitors. 3) Adam — 24/7 response capability vs competitors who miss evening/weekend deals. 4) Multiple exit strategies — can flip, BRRRR, or wholesale same deal. 5) Established title relationships — smoother closes. 6) CCG brand reputation — "close what we sign" reputation matters.','HML close time: 7-14 days. RLOC close time: 1-3 days. Time advantage vs other buyers: 4-10 days on RLOC deals. Winning deal margin: often hours, not days.','Lean into speed when competing. Offer RLOC close timeline when deal is right. "We can close in 3 business days, cash from our credit line" — very few competitors can match this.','CCG internal','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['competitive_advantage','ccg','strategy','speed']),

('CCG 10-Year Vision and Deal Volume Needed','ccg_strategy','goals','CCG 10-year goal: $100M exit value in 10 years. Path: flip volume for cash flow + BRRRR portfolio for equity + Coralstone Lending for interest income. Flip volume target: 3-4/month at $35K avg = $1.26M-1.68M/year gross profit. BRRRR portfolio target: 100+ doors at scale producing significant monthly cash flow. Annual acquisition pace: 36-48 flips + 10-15 BRRRR holds per year at target run rate.','Target flip volume: 3-4/month. Target avg profit: $35,000+/flip. Annual flip revenue target: $1.26M-1.68M. BRRRR target: 100 doors. Year 10 portfolio value: $100M+.','Every deal evaluated through lens of: does this get us to $100M? Focus on volume AND quality. Don''t cherry pick — process deals at volume and filter by criteria. Adam''s job is to ensure Caleb never misses a good deal.','CCG internal','high',NULL,ARRAY['flip','brrrr','rental','wholesale'],ARRAY['ccg_goals','strategy','vision','100m']);


-- ── MESSAGE TEMPLATES EXPANSION ──────────────────────────────
INSERT INTO message_templates (name, type, channel, wholesaler_grade, deal_type, template, variables, tone, char_count_target, notes) VALUES
('A-Grade Relationship Check — Post-Deal','relationship_check','sms','A','any','Hey {{name}} — {{address}} closed smooth. Always appreciate working with you. Got anything else in the pipeline for {{county}} County?',ARRAY['name','address','county'],'warm',110,'Post-close relationship maintenance. Send same day deal closes. Reference the specific deal.'),
('Cold Introduction Email — New Wholesaler','opening_offer','email','unknown','any','Hey {{name}},\n\nWe''re Coralstone Capital Group — active cash buyers doing 3-4 deals a month in {{counties}} Counties. We close what we sign and we close fast (7-14 days cash).\n\nLooking for 3/2+ concrete block homes in our target areas. If you''ve got anything fitting that profile, shoot it our way. We''ll run numbers same day.\n\nCaleb Blair\nCoralstone Capital Group | CCG\nTampa Bay, FL',ARRAY['name','counties'],'professional',400,'Cold email intro to new wholesaler. Professional, specific, establishes credibility.'),
('Portfolio Landlord Outreach','opening_offer','sms','unknown','rental','Hey {{name}} — saw you own several properties in {{area}}. We buy rental portfolios at fair prices, no realtor, fast close. Would you consider selling any of your rentals? — Caleb, Coralstone Capital',ARRAY['name','area'],'professional',145,'Direct outreach to landlords who might sell. Good for skip-traced landlord lists.'),
('Inherited Property Outreach','opening_offer','sms','unknown','any','Hi {{name}} — my name is Caleb with Florida Buyers. We saw you may have inherited a property in {{city}}. We make fair cash offers, handle all the paperwork, and can close in 2 weeks. Would you be open to an offer?',ARRAY['name','city'],'warm',150,'Outreach to inherited property owners. Use Florida Buyers brand for seller-facing outreach.'),
('Pre-Foreclosure Outreach','opening_offer','sms','unknown','any','Hi {{name}} — Caleb here with Florida Buyers. We help homeowners in difficult situations sell quickly for fair cash. If you need to sell your home at {{address}} without hassle, I can make an offer today. No realtor fees.',ARRAY['name','address'],'warm',150,'Pre-foreclosure outreach. Sensitive — must be empathetic and clear about helping.'),
('Tax Delinquent Outreach','opening_offer','sms','unknown','any','Hi {{name}} — we buy homes in {{city}} for cash, as-is. If you''d like to avoid further issues with the property at {{address}}, we can make a fair offer and close fast. — Caleb, Florida Buyers',ARRAY['name','city','address'],'direct',135,'Tax delinquent outreach. Reference avoiding further issues without being too explicit.'),
('Absentee Owner Outreach','opening_offer','sms','unknown','any','Hi {{name}} — we buy homes in {{city}} for cash and close fast. Saw you own the property at {{address}}. Would you consider selling? We can make an offer in 24 hours. — Caleb, Coralstone Capital',ARRAY['name','city','address'],'direct',135,'Absentee owner outreach. Direct and to the point.'),
('Wholesale Deal Blast — Email','wholesale_blast','email','any','wholesale','Subject: {{beds}}/{{baths}} CBS {{type}} in {{city}} — {{asking}} / ARV ~{{arv}}\n\nHey,\n\nGot a deal that just came across my desk:\n\n📍 {{address}}, {{city}}, FL {{zip}}\n🏠 {{beds}} bed / {{baths}} bath | {{sqft}} sqft | Built {{year}}\n💰 Asking: {{asking}}\n🎯 ARV: ~{{arv}} (based on recent comps)\n🔧 Estimated Rehab: ~{{rehab}}\n📊 Profit Potential: ~{{profit}} at asking\n\nCBS construction. {{notes}}\n\nFirst qualified buyer with EMD wins it. Reply or call me directly.\n\n— Caleb\nCoralstone Capital Group',ARRAY['beds','baths','type','city','asking','arv','address','zip','sqft','year','rehab','profit','notes'],'professional',600,'Email blast for wholesale deals. More detail than SMS. Good for investor email list.'),
('Counter with Comp Data','counter_offer','sms','any','any','{{name}} — I want to make this work. Here''s what the data shows: last {{beds}}/{{baths}} sold in that zip was ${{last_comp}} on {{comp_date}}, and before that ${{comp2}}. Our ARV of {{our_arv}} is honest. Best we can do is {{our_counter}} and we close in 10 days.',ARRAY['name','beds','baths','last_comp','comp_date','comp2','our_arv','our_counter'],'direct',155,'Counter that uses actual comp data to justify price. Very powerful credibility tool.'),
('Near-MAO Counter Final','counter_offer','sms','any','any','{{name}} — we''re at our ceiling here. {{our_final}} is the best we can do — at that number the math barely works for us. If that works, I can have a contract over today.',ARRAY['name','our_final'],'direct',120,'Final counter at or near MAO. Signals this is the limit without saying "MAO."'),
('Walk After Counter Rejected','hard_no','sms','any','any','Understood {{name}}. We can''t go higher — the numbers don''t support it. Going to move on. If circumstances change, give us a call.',ARRAY['name'],'professional',100,'Walk message when our final counter is rejected. Clean and professional.'),
('Inspection Period Extension Request','follow_up_1','sms','any','any','{{name}} — need a few more days on the inspection period to finish due diligence on {{address}}. Can we extend to {{new_date}}? Won''t slow the close date.',ARRAY['name','address','new_date'],'professional',125,'Inspection extension request. Reassure it won''t delay close.'),
('Repair Credit After Inspection','counter_offer','sms','any','any','{{name}} — inspector found {{issue}} at {{address}}. Going to need a ${{credit}} reduction to make the numbers work given the additional cost. Can we get to {{new_price}}?',ARRAY['name','issue','address','credit','new_price'],'direct',140,'Post-inspection repair credit request. Be specific about what was found and what you need.'),
('Tenant Info Request — Occupied Deal','opening_offer','sms','any','rental','{{name}} — interested in {{address}}. Is it tenant occupied? If so: current rent, lease end date, and month-to-month or fixed? Want to understand the income picture.',ARRAY['name','address'],'professional',130,'Requesting tenant info on occupied deal. Essential before offering on any occupied property.'),
('HOA Status Request','opening_offer','sms','any','any','{{name}} — quick question on {{address}}: is there an HOA? If so, monthly dues and any rental restrictions? Want to confirm before we run numbers.',ARRAY['name','address'],'professional',120,'HOA status inquiry before offering. Critical for rental/BRRRR analysis.'),
('Code Violation Discovery Response','counter_offer','sms','any','any','{{name}} — found an open code violation on {{address}} when I checked with the county. Could be a problem at closing. Can we lower to {{adjusted_price}} to account for resolution cost? Or can you clear it before close?',ARRAY['name','address','adjusted_price'],'direct',150,'Response to discovering code violation. Present options rather than just price reduction.'),
('Title Issue Response','follow_up_1','sms','any','any','{{name}} — title search came back with {{issue}} on {{address}}. Need this cleared before we can close. Can your title company handle this or do we need to extend the closing date?',ARRAY['name','issue','address'],'professional',140,'Title issue communication. Professional and problem-solving focused.'),
('Deal Won — Thank You','relationship_check','sms','any','any','{{name}} — we''re closed on {{address}}. Thanks for working with us — smooth deal. Looking forward to the next one.',ARRAY['name','address'],'warm',90,'Post-close thank you. Short and warm. Relationship maintenance.'),
('Dead Deal — Keep Us In Mind','soft_no','sms','any','any','{{name}} — not going to work on {{address}} at that price. No hard feelings — keep us in mind. We''re buying consistently and move fast when the math works.',ARRAY['name','address'],'warm',120,'Generic dead deal message. Works for any reason the deal died.'),
('Re-Engage Cold Wholesaler','relationship_check','sms','any','any','Hey {{name}} — been a minute. Hope you''re doing well. Still active and buying in {{county}} County — would love to see whatever you''ve got.',ARRAY['name','county'],'warm',100,'Re-engage wholesaler who has gone quiet. Brief and friendly.'),
('Proof of Funds — Email Version','pof_send','email','any','any','{{name}},\n\nAttached is our proof of funds for the {{address}} acquisition. We have capital ready to close. As you can see, we are well-funded and close consistently.\n\nLooking forward to getting this under contract.\n\nCaleb Blair\nCoralstone Capital Group',ARRAY['name','address'],'professional',300,'Email POF send. More formal than SMS. Attach actual POF document.'),
('Multifamily Deal Inquiry','opening_offer','sms','unknown','any','{{name}} — do you work multifamily deals in {{county}} County? Looking for 2-4 unit properties — same as SFR: cash, fast close. Shoot anything my way.',ARRAY['name','county'],'professional',115,'Expanding relationship to multifamily. Good for wholesalers who might diversify what they bring.'),
('Land Deal Inquiry','opening_offer','sms','unknown','any','{{name}} — do you work land deals? We look at lots in {{county}} County depending on size and zoning. Happy to review anything.',ARRAY['name','county'],'professional',110,'Opening for land deals. Secondary interest but worth noting.'),
('Urgent — Deal Expires Today','counter_offer','sms','any','any','{{name}} — our agreement on {{address}} expires today. Where are we? If we''re not going to close, I need to know now so I can move on.',ARRAY['name','address'],'urgent',100,'Final urgency before deal expiration. Direct and time-pressured.'),
('New Market Introduction','opening_offer','sms','unknown','any','Hey {{name}} — Caleb from Coralstone Capital. We''re expanding our buying in {{new_county}} County and looking for deals. If you work that market, I''d love to be on your buyer list. Cash, fast close.',ARRAY['name','new_county'],'professional',130,'Introducing CCG to a wholesaler in a new market area.'),
('Weekend Deal Alert','opening_offer','sms','A','any','{{name}} — deal just hit my radar. {{address}} — you know it? Want to run numbers over the weekend if you can share details.',ARRAY['name','address'],'casual',90,'Weekend outreach for urgent deals. Casual but interested tone.');

-- ── NEGOTIATION PLAYBOOK EXPANSION ──────────────────────────
INSERT INTO negotiation_playbook (situation, wholesaler_grade, deal_type, context, recommended_approach, example_script, what_not_to_do, follow_up_if_no_response, success_indicators, failure_indicators, escalate_to_caleb_if, notes) VALUES
('tenant_occupied_negotiation','any','rental','Deal has existing tenant — need to understand lease terms, rent, and tenant quality before finalizing price.','Get all tenant info upfront. Calculate if rent is at/near/above market. If below market, factor in lease duration and turnover cost. If above market, it''s a bonus.','Hey {{name}} — before we finalize, need tenant details: current rent, lease term, month-to-month or fixed, and how long tenant has been there. That affects our number.','Do not offer without tenant info. A bad tenant can cost $5,000-15,000 to remove.','If no response on tenant info request within 24h: send follow-up, note you can''t move forward without it.','Tenant is month-to-month at market rent, good history. Strong position.','Below market long-term lease, tenant with known issues. Must be priced accordingly.','If tenant situation is complex (eviction needed, very below market long-term lease)','Tenant-occupied deals have hidden costs: potential non-payment during takeover, eviction risk, needed unit turnover. Price in $3,000-10,000 risk buffer.'),
('multiple_offers_situation','any','any','Wholesaler has confirmed multiple offers on the property — real competition.','Do not panic and overpay. Assess if deal is truly exceptional. If yes, go to 94% of MAO. If not exceptional, hold position or walk. Speed matters here — offer to send contract immediately.','I hear you — we can go to {{improved_offer}} and I can have a signed contract to you within the hour. We close what we sign. That matters as much as price.','"Going to our absolute ceiling" is a trap if it''s above MAO. Always know your number before entering this conversation.','If they go with another buyer: "No worries. If it falls through, call us first."','They choose CCG based on price+speed+certainty combo.','They go to highest bidder significantly above CCG''s ceiling.','If deal is exceptional and going to 98-100% of MAO could make sense','Multiple offer situations separate buyers who close from those who don''t. CCG reputation for closing matters here. Reference past closes if relationship established.'),
('wholesaler_wants_caleb_to_call','A','any','A-grade wholesaler specifically requests to talk to Caleb before proceeding.','This is a relationship signal. Escalate to Caleb immediately. Adam''s role is to get the call set up fast.','Hey {{name}} — absolutely. Let me get Caleb on the phone with you. What''s your availability in the next hour?','Do not try to substitute for Caleb on this request. Honor the relationship.','N/A — this goes to Caleb immediately.','Caleb and wholesaler connect, deal moves forward.','Relationship feels damaged if we stall or don''t prioritize the call.','ALWAYS — this is automatic escalation to Caleb.','A-grade wholesalers sometimes want to speak to the principal. This is a relationship opportunity, not a problem.'),
('seller_still_in_home','any','flip','Property has seller still living in it — must plan for move-out at or before close.','Confirm move-out timeline explicitly in contract. Build in flexibility on close date if needed. Consider cash-for-keys if seller needs moving assistance.','{{name}} — is the seller''s move-out confirmed? We need that locked in before close. If they need a few days after close, we can work with that as long as it''s agreed in writing.','Do not assume seller will be out by close — clarify explicitly.','If seller needs extended time: cash-for-keys or post-possession agreement is the tool.','Written move-out agreement in place, seller cooperative.','Seller stalling on move-out commitment, indicating they may not leave.','If seller indicates they won''t or can''t leave before close','Post-possession agreements are possible but add risk. Budget $1,000-2,000 daily rate for seller to remain after close if needed as leverage for prompt departure.'),
('foundation_concern_discovered','any','any','During due diligence, signs of foundation issues found — cracks, sticking doors, uneven floors.','Get structural engineer opinion immediately. Do not close without engineer clearance or significant price reduction. Foundation repair ranges from $3,000 (minor) to $150,000+ (sinkhole).','{{name}} — we''ve got some concern about foundation during our DD. Getting a structural engineer in this week before we can move forward. Will let you know what we find.','"It''s probably fine" is not acceptable. Foundation issues can make a deal completely unviable.','If inspection clear: proceed. If concerning: go back to wholesaler with engineer report and price reduction request.','Engineer report shows cosmetic cracking only, no structural concern.','Engineer identifies active movement, sinkhole indication, or major structural compromise.','ALWAYS if sinkhole or major structural compromise found','Do NOT buy foundation problems without a major price concession and clear engineering sign-off. Sinkhole = do not buy in most cases.'),
('mold_found_during_inspection','any','any','Mold discovered during inspection — ranges from minor surface to major hidden infestation.','Get professional mold assessment immediately. Cost to remediate varies wildly. Request price reduction equal to remediation estimate plus 20% buffer.','{{name}} — inspector found mold in the {{location}}. Getting a remediation contractor in for an estimate. Can''t close without addressing this — will come back to you with a number.','"It''s just surface mold" — professional assessment required, not a guess.','If estimate comes back reasonable: request credit. If major: consider walking.','Minor surface mold with under $5,000 remediation estimate.','Major infestation behind walls, HVAC system, attic — $20,000+ remediation.','If mold discovery is major and affects deal viability','Florida mold = disclosure required. Even after remediation, must disclose mold history when reselling. Price this into your model.'),
('closing_delay_requested','any','any','Wholesaler or seller requests to delay closing date beyond original agreement.','Understand the reason first. If legitimate (title issue, seller situation): accommodate with clear new date. If strategic delay (waiting for better offer): clarify and hold firm.','{{name}} — understood on the delay. Can you give me the specific reason so I can plan on our end? And what''s the new close date you''re targeting?','"Sure, no problem" without understanding why — you need to know if title, seller situation, or strategic.','Get a specific new close date in writing. Extend earnest money deadline accordingly.','Clear explanation and reasonable new close date proposed.','Vague reasons, unwillingness to commit to new date, signs of shopping for better offer.','If delay seems strategic (wholesaler likely shopping deal) — Caleb should assess whether to extend or walk','When extending: update all dates in contract formally. Use amendment to purchase agreement.'),
('multiple_liens_discovered','any','any','Title search reveals multiple liens — judgments, code enforcement, HOA, IRS, mechanic.','Assess total lien amount and whether they will be cleared at closing. Get title company confirmation on resolution plan. If liens exceed negotiated price: renegotiate.','{{name}} — title came back with {{lien_details}}. Title company says these total approximately {{total_amount}}. Can you confirm these will be satisfied at close? This affects our bottom line.','Assume liens will be resolved without confirming — this assumption has killed many deals.','If wholesaler can''t resolve: renegotiate price or walk.','Clear path to lien resolution identified and confirmed.','Liens cannot or will not be cleared — deal is not viable at current price.','ALWAYS if IRS lien or lien amount exceeds $10,000','Title work sometimes surfaces lien surprises. Stay calm, work through it systematically. Most issues ARE resolvable — it just takes time and sometimes price adjustment.'),
('wholesaler_no_longer_has_deal','any','any','Wholesaler reveals they lost the deal — seller backed out or another buyer closed.','Graceful exit. Express disappointment briefly. Reinforce you want to see their next deal. Log outcome to wholesaler profile.','No worries, {{name}}. Those things happen. Keep us in mind for the next one — we close fast when we move forward.','Express frustration or blame — this is part of the business.','N/A — this deal is dead. Focus on relationship preservation.','Wholesaler commits to sending next deal CCG''s way.','Wholesaler avoids future contact — relationship damaged somehow.','Never — Adam handles this completely','Mark deal as DEAD in pipeline. Note reason. Update wholesaler profile with outcome. This is useful data.'),
('arv_range_disagreement','any','any','CCG and wholesaler have significantly different ARV views — 15%+ variance.','Pull actual comp data from Urban. Present 3 specific comparable sales. Let the data speak. Do not negotiate ARV on gut feel.','{{name}} — I know we see different ARVs here. Let me share the specific comps we''re working from: {{comp1}} sold at {{price1}} on {{date1}}, {{comp2}} sold at {{price2}}. Based on these, our ARV of {{our_arv}} is what the market actually supports.','Accept wholesaler''s ARV without evidence. If you can''t support your ARV with specific comps, Urban''s analysis may need review.','If they provide strong counter-comps: review with Urban logic and adjust if warranted.','Wholesaler acknowledges comp data, negotiation moves to price rather than ARV.','They insist on ARV without providing supporting comps — likely inflation.','If wholesaler provides significantly different comps that appear credible and change ARV by 10%+','Data wins. Present comps clearly and factually. This is not emotional — it''s math.');

-- ── ADAM LEARNINGS EXPANSION ─────────────────────────────────
INSERT INTO adam_learnings (type, context, lesson, confidence, applies_to) VALUES
('market_pattern','Tampa Bay 2024-2025 market','The best deals in Tampa Bay come from relationships, not from being the highest bidder. A-grade wholesalers give their most trusted buyers right of first refusal on their best deals before blasting to the list.','high',ARRAY['wholesale','negotiation']),
('market_pattern','Pasco County specific intel','Zephyrhills (33525) and San Antonio (33576) have the best combination of: older CBS inventory, lower competition, and strong rental demand. These should be Adam primary hunting grounds for BRRRR.','high',ARRAY['brrrr','pasco']),
('market_pattern','Hernando County specific intel','Spring Hill properties with well water and septic are common. Always budget $650 for combined well and septic inspection. Budget $3,000 for water treatment system if needed. These costs are predictable and should be standard in Hernando County scope.','high',ARRAY['brrrr','rental','hernando']),
('negotiation_outcome','Speed in Tampa Bay wholesale market','Caleb has seen deals won and lost based on response time measured in hours. The difference between closing and losing a deal often comes down to who responds to the wholesaler first, not who offers more money. Adam''s primary value is sub-30-minute response time 24/7.','high',ARRAY['negotiation','speed','competitive_advantage']),
('deal_outcome','Florida insurance market 2024','Roof age is THE critical factor in Florida property insurance in 2024. Roofs over 15 years are causing significant insurance issues — either very high premiums or uninsurable. Always identify roof age early. New roof installed during rehab dramatically improves property insurance profile and buyer appeal.','high',ARRAY['flip','brrrr','rental','insurance']),
('market_pattern','Wholesaler reliability scoring','A wholesalers who submit clean deals with accurate ARV and respond quickly to questions are far more valuable than volume submitters. Quality deal relationships compound over time. CCG should invest relationship energy in top 20% of wholesalers who produce 80% of closed deals.','high',ARRAY['wholesalers','strategy']),
('market_pattern','BRRRR vs Flip decision framework','BRRRR is the right exit when: 1) Cash left in deal is under 25%, 2) Monthly cash flow is positive after DSCR, 3) Property is in strong rental demand area, 4) Construction is CBS 1978-1999. Flip is right when: profit exceeds $40K, strong retail buyer market, or BRRRR math doesn''t work.','high',ARRAY['brrrr','flip','strategy']),
('negotiation_outcome','Code violations are negotiation leverage','When code violations are discovered during DD, they are both a risk and a negotiation tool. Present the violation professionally, get a cost estimate, and request a price reduction plus a reasonable resolution timeline. Most motivated sellers prefer this to losing the deal entirely.','high',ARRAY['negotiation','due_diligence','code_violations']),
('market_pattern','Portfolio building momentum','The first 10 BRRRR properties are the hardest. After 10+ doors, banks and lenders treat CCG as a serious portfolio operator, terms improve, relationships deepen, and deal flow from motivated sellers increases (reputation spreads). Getting from 0 to 10 doors is the critical first phase.','high',ARRAY['brrrr','portfolio','strategy']),
('deal_outcome','Concrete block construction advantage in Florida','CBS homes sell to retail buyers faster and at a premium vs frame. They cost less to insure. They''re more termite-resistant. They''re more hurricane-resistant. In Tampa Bay''s insurance market, the CBS premium over frame is significant and increasing. Always prefer CBS when choosing between similar deals.','high',ARRAY['flip','brrrr','rental','construction']),
('market_pattern','Competition identification tactic','When a deal dies to another buyer, always ask the wholesaler: "Who did you end up going with?" Over time this builds a picture of who the active competition is in Tampa Bay. Knowing who you''re competing against — their typical pricing, their speed, their reputation — helps Adam position CCG more effectively.','medium',ARRAY['wholesale','negotiation','competitive_intelligence']),
('market_pattern','Seasonal deal flow pattern','January and February are historically the highest volume months for wholesale deal flow in Tampa Bay. Estate settlements from holidays, new year decisions by motivated sellers, snowbird season bringing out-of-state activity. Adam should be most aggressive in Q1 every year.','high',ARRAY['strategy','seasonality','deal_flow']),
('negotiation_outcome','Cash for keys vs eviction','For tenant-occupied properties requiring vacancy before flip, cash for keys ($500-2,000) is almost always faster and cheaper than formal eviction ($800-2,500 plus 3-8 weeks). Offer cash for keys as first approach. Frame it as a moving assistance gift. Most tenants respond positively.','high',ARRAY['flip','brrrr','rental','tenants']),
('market_pattern','Tampa Bay rental tenant profile','Best tenants in CCG target markets: healthcare workers (USF Health, Tampa General, AdventHealth), military families (MacDill AFB proximity), established families in school zones. Target properties near these employment and demand centers for lowest vacancy and best tenant quality.','high',ARRAY['rental','brrrr','strategy']),
('market_pattern','Title company relationship value','Having a trusted, investor-friendly title company in each county is a strategic asset. They can: expedite closings, identify title issues early, assist with simultaneous closing structures, advise on complex situations. CCG should develop primary relationships in Hillsborough, Pasco, and Hernando.','high',ARRAY['flip','brrrr','rental','wholesale','title']);

COMMIT;
