-- ============================================================
-- ADAM BRAIN SEED DATA
-- Comprehensive Tampa Bay real estate intelligence
-- ============================================================

-- ── CCG ENTITY STRUCTURE ─────────────────────────────────────
INSERT INTO ccg_entities (entity_name, entity_type, primary_use, counties, deal_types, signing_authority, notes) VALUES
('Coralstone Capital Group Trust', 'trust', 'Holding entity for all CCG investments', ARRAY['Pasco','Hillsborough','Hernando','Pinellas','Polk','Sarasota'], ARRAY['flip','rental','brrrr'], 'Caleb Blair as Trustee', 'Primary acquisition entity. All properties held under trust.'),
('Florida Buyers LLC', 'llc', 'Consumer-facing acquisition brand', ARRAY['Pasco','Hillsborough','Hernando','Pinellas','Polk'], ARRAY['wholesale','flip'], 'Caleb Blair', 'flbuyers.com — direct to seller and consumer brand. Use this identity for seller-facing outreach.'),
('Coralstone Property Services', 'llc', 'Maintenance and property services', ARRAY['Pasco','Hillsborough'], ARRAY['maintenance'], 'Caleb Blair (75% Managing Member)', 'CPS — property maintenance subsidiary. Caleb is 75% Managing Member. Partnership restructuring in progress.'),
('Coralstone Lending', 'llc', 'Private lending', ARRAY['Hillsborough','Pasco','Pinellas'], ARRAY['lending'], 'Caleb Blair, Grant Patterson', 'Internal lending entity. Can fund CCG deals. Check capacity before routing to external HML.');

-- ── HUD FAIR MARKET RENTS ────────────────────────────────────
-- Tampa-St. Petersburg-Clearwater MSA FY2025
INSERT INTO hud_fmr (metro_area, county, fiscal_year, efficiency, one_br, two_br, three_br, four_br, notes) VALUES
('Tampa-St. Petersburg-Clearwater MSA', 'Hillsborough', 2025, 1566, 1686, 1978, 2533, 3082, 'HUD FMR FY2025. Use as floor estimate for rental income. Actual market rents often run 5-15% above HUD FMR in active areas.'),
('Tampa-St. Petersburg-Clearwater MSA', 'Pinellas', 2025, 1566, 1686, 1978, 2533, 3082, 'Same MSA as Hillsborough. Pinellas tends to run at or slightly above HUD rates.'),
('Tampa-St. Petersburg-Clearwater MSA', 'Pasco', 2025, 1400, 1550, 1800, 2300, 2800, 'Pasco County slightly below Tampa core MSA. Growing rapidly. Rents increasing 8-12% YoY.'),
('Hernando County HUD', 'Hernando', 2025, 1200, 1350, 1600, 2050, 2500, 'More affordable market. Hernando has significant septic/well infrastructure. Factor in utility costs.'),
('Polk County HUD', 'Polk', 2025, 1100, 1250, 1500, 1950, 2350, 'Lakeland/Winter Haven area. Lower rents, lower prices. Good CoC deals possible.'),
('Sarasota-Bradenton MSA', 'Sarasota', 2025, 1800, 2000, 2400, 3100, 3800, 'Premium market. Higher rents but higher prices. Harder to make BRRRR work.');

-- ── MARKET AREAS - PASCO COUNTY ─────────────────────────────
INSERT INTO market_areas (county, city, zip_code, median_sale_price, avg_price_per_sqft, avg_rent_3br, avg_rent_2br, hud_fmr_3br, avg_days_on_market, months_of_inventory, list_to_sale_ratio, investor_buyer_pct, flood_zone_prevalence, yoy_appreciation_pct, competition_level, ccg_priority, ccg_notes) VALUES
('Pasco', 'Zephyrhills', '33525', 255000, 155, 1750, 1450, 2300, 22, 2.1, 0.97, 35, 'low', 8.5, 'medium', 'primary', 'Strong CCG territory. Concrete block inventory from 1985-1995. Good wholesale and BRRRR market. Derek sends deals here frequently.'),
('Pasco', 'Wesley Chapel', '33544', 390000, 195, 2150, 1800, 2300, 18, 1.8, 0.98, 25, 'low', 11.2, 'high', 'primary', 'High growth area. Newer construction. Good flip market. Competition is higher. Need to move fast.'),
('Pasco', 'Wesley Chapel', '33545', 345000, 175, 2000, 1650, 2300, 20, 1.9, 0.97, 28, 'low', 10.1, 'medium', 'primary', 'Good flip area. Mix of older and newer. Concrete block 90s homes are ideal targets.'),
('Pasco', 'Lutz', '33559', 385000, 192, 2200, 1850, 2300, 16, 1.6, 0.99, 22, 'low', 12.0, 'high', 'secondary', 'Premium Pasco. Higher prices make MAO math harder. Only exceptional deals.'),
('Pasco', 'Land O Lakes', '34637', 375000, 188, 2050, 1700, 2300, 17, 1.7, 0.98, 24, 'low', 11.5, 'medium', 'primary', 'Growing suburb. Good retail buyer demand. Strong flip exit market.'),
('Pasco', 'Land O Lakes', '34638', 365000, 183, 2000, 1650, 2300, 19, 1.8, 0.97, 26, 'low', 10.8, 'medium', 'primary', 'Similar to 34637. Solid market.'),
('Pasco', 'Land O Lakes', '34639', 358000, 179, 1980, 1620, 2300, 21, 2.0, 0.97, 28, 'low', 9.5, 'medium', 'primary', 'Slightly more affordable LOL. Good balance of price/demand.'),
('Pasco', 'New Port Richey', '34652', 238000, 145, 1700, 1400, 2300, 25, 2.5, 0.96, 38, 'medium', 6.5, 'medium', 'primary', 'Older inventory. Lots of concrete block 1975-1990. Strong wholesale and rental play. Flood zones in coastal areas - check carefully.'),
('Pasco', 'New Port Richey', '34653', 218000, 138, 1650, 1350, 2300, 28, 2.8, 0.95, 42, 'medium', 5.8, 'low', 'primary', 'Lower price point. Good wholesale deals. Some flood zone issues near Gulf.'),
('Pasco', 'New Port Richey', '34654', 252000, 151, 1750, 1450, 2300, 24, 2.3, 0.96, 36, 'low', 7.2, 'medium', 'primary', 'East NPR. Better flood zone profile. Good BRRRR territory.'),
('Pasco', 'Trinity', '34655', 378000, 191, 2150, 1800, 2300, 16, 1.5, 0.99, 18, 'low', 12.5, 'high', 'secondary', 'Premium west Pasco. High demand, lower investor presence. Good flip exits but harder entry.'),
('Pasco', 'Hudson', '34667', 222000, 140, 1600, 1300, 2300, 30, 3.0, 0.95, 40, 'high', 4.5, 'low', 'watch', 'More coastal flood zone risk. Older demographic. Slower appreciation. Proceed with caution.'),
('Pasco', 'Port Richey', '34668', 212000, 134, 1550, 1280, 2300, 32, 3.2, 0.94, 42, 'high', 4.0, 'low', 'watch', 'Similar concerns to Hudson. Heavy flood zone. Not primary territory.'),
('Pasco', 'Hudson', '34669', 237000, 146, 1650, 1380, 2300, 27, 2.6, 0.96, 38, 'medium', 6.0, 'low', 'watch', 'Inland Hudson. Better than coastal. Still cautious on flood and demographics.'),
('Pasco', 'San Antonio', '33576', 312000, 159, 1850, 1500, 2300, 23, 2.2, 0.97, 32, 'low', 8.0, 'primary', 'Good rural Pasco. Older concrete block inventory. Less competition. Good BRRRR deals come through here.'),
('Pasco', 'Dade City', '33523', 248000, 148, 1700, 1400, 2300, 26, 2.4, 0.96, 35, 'low', 6.5, 'medium', 'primary', 'Small market but deals exist. Less competition than Wesley Chapel. Worth monitoring.'),
('Pasco', 'Odessa', '33556', 498000, 245, 2500, 2100, 2300, 14, 1.2, 0.99, 15, 'low', 15.0, 'high', 'secondary', 'Premium west Hillsborough/Pasco border. Very high prices. Only exceptional deals at significant discount.'),

-- ── MARKET AREAS - HILLSBOROUGH COUNTY ──────────────────────
('Hillsborough', 'Ruskin', '33570', 298000, 158, 1900, 1600, 2533, 20, 1.9, 0.97, 32, 'low', 9.5, 'medium', 'primary', 'Caleb target area. South Hillsborough. Good mix of ages. Strong rental demand from USF/Port area workers.'),
('Hillsborough', 'Sun City Center', '33573', 278000, 152, 1750, 1450, 2533, 24, 2.2, 0.96, 28, 'low', 7.5, 'medium', 'primary', 'Age-restricted to 55+. Different buyer profile. Some good deals. Check HOA on every deal here.'),
('Hillsborough', 'Apollo Beach', '33572', 388000, 195, 2200, 1850, 2533, 17, 1.6, 0.98, 22, 'low', 12.0, 'medium', 'secondary', 'Higher end coastal south Hillsborough. Good appreciation but flood zone risk. Check FEMA maps always.'),
('Hillsborough', 'Riverview', '33569', 342000, 171, 2050, 1700, 2533, 18, 1.7, 0.98, 26, 'low', 10.5, 'high', 'primary', 'Hot market. Strong retail buyer demand. Great flip exit. Competition has increased significantly.'),
('Hillsborough', 'Riverview', '33578', 332000, 167, 2000, 1650, 2533, 19, 1.8, 0.97, 27, 'low', 10.0, 'high', 'primary', 'Similar to 33569. Slightly more affordable. Same competitive dynamics.'),
('Hillsborough', 'Riverview', '33579', 358000, 179, 2100, 1750, 2533, 17, 1.6, 0.98, 24, 'low', 11.2, 'high', 'primary', 'Newer Riverview. Strong growth. Premium retail exit possible.'),
('Hillsborough', 'Brandon', '33510', 312000, 161, 1950, 1600, 2533, 19, 1.8, 0.97, 30, 'low', 9.0, 'medium', 'primary', 'Established market. Good inventory of 80s-90s concrete block. Strong rental demand.'),
('Hillsborough', 'Brandon', '33511', 332000, 168, 2000, 1650, 2533, 18, 1.7, 0.98, 28, 'low', 9.5, 'medium', 'primary', 'East Brandon. Slightly stronger than 33510. Good exit market.'),
('Hillsborough', 'Valrico', '33594', 342000, 172, 2050, 1700, 2533, 17, 1.6, 0.98, 25, 'low', 10.0, 'medium', 'primary', 'Good suburban market. Less investor saturation than Brandon. Worth pursuing.'),
('Hillsborough', 'Valrico', '33596', 355000, 178, 2100, 1750, 2533, 16, 1.5, 0.98, 23, 'low', 10.8, 'medium', 'primary', 'Stronger Valrico. Good retail exit. Somewhat competitive.'),
('Hillsborough', 'Dover', '33527', 298000, 153, 1850, 1520, 2533, 22, 2.0, 0.97, 32, 'low', 8.5, 'medium', 'primary', 'East Hillsborough. Less competitive. Older inventory. Some deals come through here.'),
('Hillsborough', 'Seffner', '33584', 282000, 148, 1800, 1480, 2533, 23, 2.2, 0.96, 34, 'low', 8.0, 'medium', 'primary', 'Underappreciated market. Older concrete block. Good BRRRR opportunity.'),
('Hillsborough', 'Thonotosassa', '33592', 318000, 161, 1900, 1550, 2533, 21, 2.0, 0.97, 30, 'low', 8.8, 'low', 'primary', 'Rural feel but close to Tampa. Less competition. Larger lots common. Good for certain buyer profiles.'),
('Hillsborough', 'Plant City', '33566', 288000, 150, 1820, 1480, 2533, 22, 2.1, 0.97, 32, 'low', 8.0, 'medium', 'secondary', 'East Hillsborough. Growing but different market dynamics. Check before pursuing.'),
('Hillsborough', 'Plant City', '33567', 268000, 143, 1750, 1420, 2533, 24, 2.3, 0.96, 34, 'low', 7.5, 'low', 'secondary', 'Less competitive Plant City. Older inventory. Some deals possible.'),
('Hillsborough', 'Gibsonton', '33534', 282000, 148, 1820, 1500, 2533, 23, 2.2, 0.96, 33, 'medium', 7.2, 'medium', 'watch', 'Some flood zone concerns near Alafia River. Check carefully. Otherwise decent market.'),
('Hillsborough', 'Wimauma', '33598', 272000, 143, 1750, 1420, 2533, 24, 2.3, 0.96, 35, 'low', 7.0, 'low', 'watch', 'Rural south Hillsborough. Growing but slower. Some agricultural area concerns.'),
('Hillsborough', 'Lithia', '33547', 452000, 218, 2400, 2000, 2533, 15, 1.4, 0.99, 18, 'low', 13.5, 'very_high', 'secondary', 'Fishhawk area. Very high demand, premium prices. Very hard to make flip math work. Only exceptional deals.'),

-- ── MARKET AREAS - HERNANDO COUNTY ──────────────────────────
('Hernando', 'Spring Hill', '34606', 232000, 140, 1650, 1350, 2050, 25, 2.4, 0.96, 36, 'low', 6.8, 'low', 'primary', 'Core Spring Hill. Lots of concrete block 1980-1995 inventory. Less competition. Good BRRRR and rental territory. Spring Hill has many septics - factor into analysis.'),
('Hernando', 'Spring Hill', '34607', 248000, 147, 1700, 1400, 2050, 23, 2.2, 0.96, 34, 'medium', 7.2, 'low', 'primary', 'Spring Hill coastal. Some flood zone near Weeki Wachee. Otherwise good market. Check FEMA maps.'),
('Hernando', 'Spring Hill', '34608', 252000, 149, 1720, 1420, 2050, 22, 2.1, 0.97, 33, 'low', 7.5, 'low', 'primary', 'Best Spring Hill zip. Less flood, more retail demand. Good flip exit possible.'),
('Hernando', 'Spring Hill', '34609', 258000, 151, 1750, 1450, 2050, 21, 2.0, 0.97, 32, 'low', 7.8, 'medium', 'primary', 'East Spring Hill. Growing area. Better appreciation than western zips.'),
('Hernando', 'Brooksville', '34601', 228000, 138, 1620, 1330, 2050, 27, 2.6, 0.95, 38, 'low', 6.2, 'low', 'secondary', 'Rural character. Less liquid exit market. Longer hold times. Proceed carefully.'),
('Hernando', 'Brooksville', '34602', 218000, 133, 1580, 1290, 2050, 29, 2.8, 0.95, 40, 'low', 5.8, 'low', 'secondary', 'More rural Brooksville. Slower market. Only exceptional deals worth pursuing.'),
('Hernando', 'Brooksville', '34613', 242000, 143, 1680, 1380, 2050, 25, 2.4, 0.96, 36, 'low', 6.8, 'low', 'secondary', 'Spring Hill adjacent Brooksville. Better than core Brooksville. Some deals possible.'),

-- ── MARKET AREAS - PINELLAS COUNTY ──────────────────────────
('Pinellas', 'Clearwater', '33755', 298000, 185, 1950, 1600, 1978, 18, 1.6, 0.98, 28, 'low', 9.5, 'high', 'secondary', 'Good market but expensive. Flood zone is major consideration near coast. Inland properties better for investors.'),
('Pinellas', 'Largo', '33771', 272000, 168, 1820, 1500, 1978, 20, 1.8, 0.97, 30, 'medium', 8.8, 'medium', 'secondary', 'Central Pinellas. Some good deals come through. Higher competition.'),
('Pinellas', 'Pinellas Park', '33782', 258000, 159, 1750, 1440, 1978, 21, 1.9, 0.97, 32, 'low', 8.5, 'medium', 'secondary', 'More affordable Pinellas. Some investor opportunity. Secondary market for CCG.'),
('Pinellas', 'Seminole', '33772', 318000, 190, 2000, 1650, 1978, 17, 1.5, 0.98, 26, 'low', 10.5, 'high', 'secondary', 'Strong market. High demand. Higher competition makes entry difficult.'),
('Pinellas', 'St. Petersburg', '33710', 282000, 172, 1900, 1580, 1978, 19, 1.7, 0.98, 28, 'medium', 9.0, 'high', 'secondary', 'South St. Pete. Good market but competitive. Some flood zone risk.'),

-- ── MARKET AREAS - POLK COUNTY ──────────────────────────────
('Polk', 'Lakeland', '33805', 218000, 128, 1550, 1280, 1950, 25, 2.4, 0.96, 36, 'low', 7.2, 'low', 'secondary', 'Older Lakeland. Less competitive. Some deals come through from regional wholesalers. Different buyer profile.'),
('Polk', 'Lakeland', '33810', 252000, 145, 1700, 1400, 1950, 22, 2.1, 0.97, 33, 'low', 8.0, 'medium', 'secondary', 'North Lakeland. Better than 33805. Growing area near I-4 corridor.'),
('Polk', 'Winter Haven', '33880', 225000, 132, 1580, 1300, 1950, 24, 2.3, 0.96, 35, 'low', 7.0, 'low', 'secondary', 'Chain of Lakes area. Different market. Less CCG focus but some opportunities.');

-- ── REHAB COST BENCHMARKS ────────────────────────────────────
INSERT INTO rehab_costs (trade, item, scope, unit, cost_low, cost_mid, cost_high, florida_specific_notes, common_hidden_costs, typical_overrun_pct, red_flags, inspector_notes) VALUES
-- ROOF
('Roof', 'Asphalt Shingle Replacement', 'full', 'per_home', 9000, 13000, 18000, 'Florida requires enhanced wind resistance. 130 mph rated shingles in most counties. Peel-and-stick underlayment now code in many areas.', 'Rotted decking adds $1,500-4,000. Check for multiple layers - Florida allows only one re-roof before tear-off required.', 15, 'Multiple layers, visible sagging, soft spots, active leaks, improper flashing', 'Always get on the roof or use drone. Age and nail pattern matter for insurance.'),
('Roof', 'Metal Roof Replacement', 'full', 'per_home', 16000, 22000, 35000, 'Metal preferred by insurance companies - can reduce premiums 15-25%. Better long-term. Justifiable on BRRRR holds.', 'Decking replacement commonly needed. Flashing and trim add cost.', 12, 'Previous improper installation, rust spots, loose panels', 'Wind mitigation credits for metal roofs are significant. Worth considering on holds.'),
('Roof', 'Roof Repair/Patch', 'repair', 'per_home', 800, 2500, 6000, 'Minor repairs often band-aids. If roof is 15+ years old, factor full replacement in your numbers even if patch seems feasible.', 'Hidden damage often discovered during repair - escalates to replacement.', 50, 'Age over 15 years, missing shingles, granule loss in gutters', 'If insurance claim involved, must disclose. Check permit history.'),
('Roof', 'Flat/TPO Roof', 'full', 'per_home', 8000, 14000, 22000, 'Common on Florida additions and older homes. TPO is preferred material. EPDM less common.', 'Decking replacement, drainage issues', 20, 'Ponding water, blistering, alligatoring of old tar', 'Critical to get properly pitched - ponding causes premature failure in Florida rain.'),

-- HVAC
('HVAC', 'Full HVAC Replacement (3-ton central)', 'full', 'per_home', 7500, 10000, 14000, 'Florida HVAC lifespan is 12-15 years vs national 15-20 due to continuous heavy use. Budget accordingly.', 'Ductwork replacement adds $3,000-6,000 if needed. Permit required in most Florida counties.', 15, 'Unit over 12 years, R-22 refrigerant (obsolete), rust, frequent repairs', 'Always run unit and check airflow to every room. Note brand - Bryant/Carrier/Lennox preferred.'),
('HVAC', 'HVAC Repair', 'repair', 'per_home', 400, 1500, 4000, 'Common repairs: capacitors $200-400, compressor $1,500-3,000, coil leaks $1,000-2,500', 'Old refrigerant types (R-22) must be replaced entirely - no recharge available.', 40, 'Old unit, repeated repairs, high utility bills', 'If capacitor replaced recently, unit may still have life. Compressor replacement on old unit = replace whole unit.'),
('HVAC', 'Ductwork Replacement', 'full', 'per_home', 3000, 5000, 8000, 'Florida duct systems in attics degrade quickly from heat. Flex duct common in 80s-90s homes.', 'Mold in ducts common in humid climate - adds remediation cost.', 20, 'Torn flex duct visible, mold smell from vents, poor airflow distribution', 'New HVAC with old duct defeats the purpose. Budget both if ducts are 20+ years old.'),
('HVAC', 'Mini-Split System', 'replacement', 'per_home', 4000, 7000, 12000, 'Good for additions, garages, or older homes without central air. Brands: Daikin, Mitsubishi preferred.', 'Electrical upgrade may be needed', 10, 'Window units only (no central system)', 'Mini-splits are viable rental option. Reduces cost vs full central air.'),

-- PLUMBING
('Plumbing', 'Full Re-Pipe (PEX)', 'full', 'per_home', 5000, 8000, 14000, 'PEX is preferred material. Faster install, more flexible, freeze-resistant (though less critical in FL).', 'Patching drywall after re-pipe adds $1,000-3,000. Permit required.', 15, 'Galvanized pipes (pre-1970), polybutylene (gray plastic, 1978-1995), active leaks, low pressure', 'Run all faucets. Check under sinks and at water heater connections. Look for galvanized at water meter connection.'),
('Plumbing', 'Water Heater Replacement', 'replacement', 'each', 900, 1400, 2200, 'Standard tank: $900-1,400. Tankless: $1,800-3,500. Check age - anything 12+ years replace.', 'Gas line issues if converting to gas. Expansion tank often required by code.', 5, 'Rust, leaking, older than 12 years, original to house', 'Note gas vs electric. Gas water heater in FL usually means natural gas or propane is available.'),
('Plumbing', 'Toilet Replacement', 'replacement', 'each', 200, 350, 600, 'Budget $200-350 per toilet installed. Always replace on full gut. Running toilets waste water.', 'Flange condition often hidden', 5, 'Running constantly, cracked tank/bowl, wobbly', 'Check subfloor condition when replacing - water damage common around toilets.'),
('Plumbing', 'Septic System Service', 'repair', 'per_home', 500, 1500, 15000, 'Critical in Hernando, rural Pasco, rural Hillsborough. Pump every 3-5 years. Full replacement is $8,000-15,000+.', 'Drain field failure is catastrophic. County inspection required on sale in some areas.', 50, 'Odor in yard, wet soggy areas over drain field, slow drains throughout house', 'Hernando County has many septic systems. Always ask about septic vs sewer on rural or older properties.'),
('Plumbing', 'Minor Plumbing Repairs', 'repair', 'per_home', 500, 1500, 4000, 'Faucets, drains, supply lines, basic repairs', 'Rotted subfloor from leaks discovered during repair', 25, 'Multiple slow drains, musty smells, water stains on ceilings', 'Budget $1,500 for plumbing repairs on a cosmetic flip as standard contingency.'),

-- ELECTRICAL
('Electrical', 'Panel Upgrade to 200A', 'replacement', 'each', 1800, 2800, 4500, 'Required for most modern updates. Essential for EV charging, modern appliances. Permit always required.', 'Meter base replacement often needed (+$500). POCO coordination for power shutoff.', 15, 'Federal Pacific Stab-Lok (fire hazard), Zinsco/Sylvania, fuses, undersized service, aluminum wiring', 'Check brand: Federal Pacific and Zinsco panels are safety hazards - disclose to buyer.'),
('Electrical', 'Full Rewire', 'full', 'per_home', 8000, 12000, 20000, 'Needed for aluminum wiring homes (1965-1973) or knob-and-tube. Permit required. Major disruption.', 'Drywall repair after pulling wire adds $2,000-5,000', 20, 'Aluminum wiring (silvery color at outlets), knob-and-tube, burnt smells, tripping breakers', 'Aluminum wiring is insurable but most buyers and insurance companies want copper.'),
('Electrical', 'GFCI/Outlet/Switch Updates', 'repair', 'per_home', 500, 1500, 3000, 'Required in kitchens, baths, garage, exterior. Code requirement on any permit work.', 'Sometimes triggers full update requirement', 10, 'Two-prong outlets throughout, ungrounded wiring', 'Budget $500-1,500 for a cosmetic flip to update visible electrical.'),
('Electrical', 'Electrical Repair/Misc', 'repair', 'per_home', 500, 2000, 5000, 'Covers various repairs, circuit additions, light fixture replacement', NULL, 15, 'Frequently tripping breakers, burning smell, hot outlets or switch plates', 'Include $1,000 electrical budget on every flip as standard contingency.'),

-- KITCHEN
('Kitchen', 'Cosmetic Kitchen Update', 'light', 'per_home', 5000, 9000, 14000, 'Paint cabinets, new hardware, new countertops (laminate), new faucet, appliances. Maximum budget on sub-$300K flips.', 'Cabinet boxes must be solid. If boxes are damaged, escalates to medium or full.', 15, 'Cabinet box damage, outdated layout that cannot work with cosmetic update', 'Most effective dollar spend in a flip. Focus on countertops and appliances for maximum impact.'),
('Kitchen', 'Mid-Range Kitchen Remodel', 'medium', 'per_home', 14000, 22000, 32000, 'New cabinets (stock/semi-custom), quartz or granite countertops, new appliances, tile backsplash. Appropriate for $350-500K flips.', 'Cabinet delivery lead times can delay project. Order early.', 20, 'Structural wall issues, plumbing relocation needed', 'Quartz countertops are table stakes for $400K+ flip buyers in Tampa Bay.'),
('Kitchen', 'Full Kitchen Gut/Custom', 'full', 'per_home', 25000, 40000, 65000, 'Custom cabinets, high-end appliances, full layout change. Only for luxury flips $600K+.', 'Layout changes require plumbing/electrical relocation - adds $5,000-15,000', 25, NULL, 'Rarely justified in CCG target markets. Budget accordingly.'),
('Kitchen', 'Appliance Package', 'replacement', 'per_home', 2200, 3500, 6000, 'Stainless: range, dishwasher, microwave (above range or built-in), refrigerator. Samsung, LG, GE preferred for resale. Buy package deals at Lowe''s/Home Depot.', NULL, 5, 'Worn, mismatched, non-stainless appliances will kill buyer first impressions', 'Refrigerator: include for rentals, include on flips if ARV above $350K.'),

-- BATHROOMS
('Bathrooms', 'Cosmetic Bathroom Update', 'light', 'per_bath', 2500, 5000, 8000, 'New vanity, toilet, paint, fixtures, mirror, light bar. Refinish or retile tub surround. Works on most flips.', 'Subfloor damage around toilet/tub is common and hidden', 20, 'Tile damage, wet subfloor, old fiberglass tub delaminating', 'Budget $3,500 per bath cosmetic refresh as standard flip line item.'),
('Bathrooms', 'Full Bathroom Gut', 'full', 'per_bath', 8000, 14000, 22000, 'New everything: shower/tub, tile, vanity, toilet, plumbing fixtures, exhaust fan. For premium flips or when bathroom is truly destroyed.', 'Shower pan replacement, subfloor issues', 25, 'Active leaks, mold, tile completely failed', 'Frame and rough-in: budget additional 2 weeks of timeline.'),

-- FLOORING
('Flooring', 'Luxury Vinyl Plank (LVP)', 'full', 'sqft', 2.80, 3.80, 5.20, 'Most popular choice for Florida flips. Water-resistant, durable, looks great. 6mm+ thick. Use same throughout living areas for clean look.', 'Subfloor leveling adds $0.50-2.00/sqft if needed', 10, 'Concrete slab with moisture issues (common in FL), extreme height variation', 'Shaw or LifeProof (Home Depot) are reliable brands. Order 10% overage.'),
('Flooring', 'Tile (Ceramic/Porcelain)', 'full', 'sqft', 4.50, 7.00, 12.00, 'Great for Florida - durable, cool underfoot, moisture resistant. Common in kitchens, baths, entries. Labor-intensive.', 'Subfloor prep critical. Cracked tile after install = improper prep.', 15, 'Uneven slab, moisture in slab', 'Large format tile (12x24 or bigger) is current buyer preference in $350K+ market.'),
('Flooring', 'Carpet (Bedrooms Only)', 'full', 'sqft', 1.80, 3.00, 5.00, 'Limit carpet to bedrooms only. Buyers increasingly want hard surface throughout but budget limits often require carpet in bedrooms.', NULL, 5, NULL, 'Install LVP or tile throughout if ARV supports it. Carpet in bedrooms only for budget flips.'),
('Flooring', 'Subfloor Repair/Leveling', 'repair', 'sqft', 3.00, 6.00, 12.00, 'Concrete slab cracking, moisture damage, soft spots. Very common in older Florida homes.', 'Hidden extent often worse than initially visible', 40, 'Soft spots when walking, visible sag, areas that feel hollow, water stains on old vinyl', 'Budget $2,000 subfloor contingency on every pre-2000 home.'),

-- PAINT
('Paint', 'Interior Paint (Full House)', 'full', 'per_home', 3000, 5000, 8000, 'Walls, ceilings, trim, doors. Two coats. Price increases with ceiling height and custom trim work.', 'Popcorn ceiling removal adds $1.50-3.00/sqft if needed.', 10, 'Heavy patching needed, lead paint (pre-1978 homes), major staining', 'Popcorn ceilings test for asbestos if pre-1980 (required before disturbing). Budget $2,000-4,000 for removal.'),
('Paint', 'Exterior Paint', 'full', 'per_home', 3500, 6000, 10000, 'Concrete block: paint peels if not properly prepped. Must use elastomeric paint. Stucco painting is specialty work.', 'Wood rot repair on soffits, fascia, window trim discovered during prep', 20, 'Peeling, bubbling, efflorescence (white salt deposits), wood rot at trim', 'In FL, exterior paint every 7-10 years on concrete block. Include pressure wash in scope.'),

-- LANDSCAPING
('Landscaping', 'Basic Cleanup and Refresh', 'light', 'per_home', 800, 2000, 5000, 'Mow, edge, trim, mulch, clean up. Some new plants at entry. Pressure wash driveway and sidewalk.', 'Irrigation system repair adds $500-2,000 if broken', 10, 'Massive tree removal needed, drainage issues, dead landscaping throughout', 'Never underestimate curb appeal. $1,500 on landscaping can make or break an offer price.'),
('Landscaping', 'Full Landscaping Refresh', 'full', 'per_home', 4000, 8000, 15000, 'New sod, plants, mulch, irrigation repair/install, landscape lighting at entry. For premium flips or complete dead landscaping.', 'Tree removal, stump grinding', 15, 'Dead trees too close to house, erosion, zero curb appeal', 'Sod in Florida: Bahia (cheap, low maintenance), St. Augustine (thick, green, more expensive). Use St. Augustine for flips.'),

-- WINDOWS AND DOORS
('Windows/Doors', 'Impact Window Replacement', 'full', 'per_home', 12000, 18000, 30000, 'REQUIRED in coastal counties. Mandatory within 1 mile of coast in most FL counties post-2001. Strong insurance discount.', 'Permit always required. Hurricane straps often inspected at same time.', 15, 'Missing impact windows in areas that require them, broken seals, fogging', 'Major insurance savings - often $1,500-3,000/year reduction. Mention to buyers.'),
('Windows/Doors', 'Standard Vinyl Window Replacement', 'full', 'per_home', 6000, 10000, 16000, 'Non-impact but improved efficiency. Double-pane throughout. Appropriate for inland properties where impact not required.', NULL, 10, 'Broken seals, fogging, single-pane throughout on older home', 'Check if county requires impact or just upgraded windows.'),
('Windows/Doors', 'Front Door Replacement', 'replacement', 'each', 800, 1500, 3000, 'Front door is major first impression. Steel or fiberglass preferred. Insulated. Impact-rated if required.', NULL, 5, 'Old hollow core entry doors, damaged frame', 'Budget $1,200 for solid door with new hardware on any flip.'),
('Windows/Doors', 'Sliding Glass Door Replacement', 'replacement', 'each', 1500, 2800, 5500, 'Very common in Florida homes. Impact or non-impact. Standard size: 6-foot or 8-foot.', 'Frame condition and track damage hidden', 10, 'Difficult to open/close, broken lock, fogged glass', 'Test operation on every inspection. Budget replacement if more than 15 years old.'),

-- PERMITS AND MISC
('Permits/Admin', 'Building Permits and Inspections', 'full', 'per_home', 1500, 3000, 6000, 'Florida permit costs: structural/addition $2,000-8,000, reroofing $200-500, HVAC $150-350, electrical $200-400, plumbing $150-300. Impact fees additional for new construction.', 'Impact fees for additions can be substantial. Check before scope change.', 10, 'Open permits from previous owners - ALWAYS pull permit history before purchasing', 'Check permit status at county building dept for every deal. Unpermitted work = liability.'),
('Misc', 'Contingency Budget', 'full', 'per_home', 3000, 6000, 12000, 'Add 10-15% of hard costs as contingency. Florida homes hide surprises - mold, termites, Chinese drywall, foundation cracks, underground oil tanks.', 'Chinese drywall (2004-2007 construction or imports): corrosive smell, black AC coils, immediate red flag', 0, 'Any home 1960-1975 for lead/asbestos. 2004-2007 imports for Chinese drywall. Any moisture smell.', 'NEVER skip contingency. It is not optional. It is a cost of doing business.'),
('Misc', 'Termite Treatment and Damage', 'repair', 'per_home', 500, 2000, 15000, 'Subterranean and drywood termites common in FL. Treatment: $500-1,500. Damage repair: $2,000-15,000+.', 'Structural damage extent often unknown until opened up', 50, 'Mud tubes on foundation, hollow sound when knocking on wood, termite frass (pellets), wings near windows', 'Get termite inspection (WDO) on every deal. Negotiate repair credit if active infestation.'),
('Misc', 'Mold Remediation', 'repair', 'per_home', 2000, 7000, 25000, 'Florida climate + moisture = mold. Small area ($2K-4K). Larger areas or hidden in walls/attic ($10K-25K+). Disclosure required.', 'Full extent often hidden behind walls. Open and inspect suspicious areas before buying.', 60, 'Musty smell, visible black or green spots, water staining, high humidity readings inside home', 'Mold remediation contractor required. Causes: roof leak, plumbing leak, AC condensate, improper vapor barrier.'),
('Misc', 'Pool Repair and Resurfacing', 'repair', 'per_home', 2000, 8000, 20000, 'Pool adds value in FL but also cost. Resurfacing: $4,000-10,000. Equipment: $2,000-5,000. Safety fence: $2,000-4,000.', 'Structural cracks can be catastrophic - get pool inspection', 30, 'Green water, equipment failure, cracks in shell, missing safety barrier', 'Pool adds approximately $15,000-30,000 to ARV in CCG target markets. Worth maintaining/repairing if in good shape.');

-- ── CCG BUY CRITERIA ─────────────────────────────────────────
INSERT INTO buy_criteria (deal_type, label, min_beds, min_baths, min_sqft, max_sqft, preferred_construction, year_built_min, year_built_max, property_types, min_profit, min_profit_pct, min_roi_pct, max_purchase_price, hml_rate_pct, hml_ltv, hml_points, preferred_counties, acceptable_counties, max_distance_from_tampa_miles, avoid_flood_zones, avoid_hoa, notes) VALUES
('flip', 'CCG Standard Flip', 3, 2, 1100, 3200, ARRAY['concrete_block','frame'], 1975, 2010, ARRAY['sfr'], 30000, 10, 25, 400000, 9.5, 90, 2, ARRAY['Pasco','Hillsborough','Hernando'], ARRAY['Pinellas','Polk'], 60, TRUE, FALSE, 'Core flip business. Buy at MAO (70% ARV minus repairs). Full retail rehab. 4-6 month cycle. Target $35K+ avg profit. Concrete block preferred but frame acceptable. $30K minimum profit absolute floor.'),
('brrrr', 'CCG BRRRR Portfolio Builder', 3, 2, 1100, 2200, ARRAY['concrete_block'], 1978, 1999, ARRAY['sfr'], 0, 0, 0, 300000, 9.5, 90, 2, ARRAY['Pasco','Hernando','Hillsborough'], ARRAY['Pinellas','Polk'], 60, TRUE, FALSE, 'Portfolio building via BRRRR. Concrete block REQUIRED. 1978-1999 builds. Within 1 hour Tampa. Refi at 6.75% DSCR, 75% LTV. Goal: leave <20% cash in deal, positive cash flow after refi. Primary zips: Zephyrhills, Wesley Chapel, Spring Hill, Ruskin, East Hillsborough.'),
('rental', 'CCG Standard Rental', 3, 2, 1100, 2000, ARRAY['concrete_block','frame'], 1978, 2005, ARRAY['sfr'], 0, 0, 0, 280000, 9.5, 90, 2, ARRAY['Pasco','Hernando','Hillsborough'], ARRAY['Pinellas','Polk'], 60, TRUE, FALSE, 'Buy-and-hold rental. DSCR loan at 6.75%, 75% LTV. Minimum positive cash flow after DSCR payment. Property management at 10%. Must work as rental from day 1 - not just hoping for appreciation.'),
('wholesale', 'CCG Wholesale Assignment', 3, 2, 900, 3000, ARRAY['concrete_block','frame'], 1970, 2015, ARRAY['sfr','duplex'], 15000, 0, 0, 350000, 9.5, 90, 2, ARRAY['Pasco','Hillsborough','Hernando','Pinellas'], ARRAY['Polk'], 75, FALSE, FALSE, 'Lock at 60-65% ARV minus repairs maximum. Assignment fee target $15,000-30,000. Speed is everything - must move within 14 days. Have buyer before or at time of lock. Broader criteria than flip since passing to flipper buyer.');

-- Insert BRRRR specific details
UPDATE buy_criteria SET 
  brrrr_refi_rate = 6.75,
  brrrr_refi_ltv = 75,
  brrrr_max_cash_left_in_pct = 25,
  brrrr_min_cashflow_after_dscr = 0,
  brrrr_target_cashflow = 200
WHERE deal_type = 'brrrr';

UPDATE buy_criteria SET
  rental_dscr_rate = 6.75,
  rental_dscr_ltv = 75,
  rental_min_cashflow = 0,
  rental_target_cashflow = 150
WHERE deal_type = 'rental';

UPDATE buy_criteria SET
  wholesale_min_assignment_fee = 15000,
  wholesale_max_buy_pct_arv = 65
WHERE deal_type = 'wholesale';

-- ── NEGOTIATION PLAYBOOK ─────────────────────────────────────
INSERT INTO negotiation_playbook (situation, wholesaler_grade, deal_type, context, recommended_approach, example_script, what_not_to_do, follow_up_if_no_response, success_indicators, failure_indicators, escalate_to_caleb_if, notes) VALUES
('opening_offer', 'A', 'any', 'First contact with trusted wholesaler on a new deal', 'Be direct and personal. Show interest but dont reveal max. Use their name. Reference relationship history if applicable. Keep it short - under 3 sentences on text.', 'Hey {name} - saw the {address} deal come through. Looks interesting. What''s your best number? We move fast, all cash.', 'Do not reveal MAO. Do not apologize for offering below ask. Do not send a formal letter for initial text contact.', 'If no response in 4 hours: "Hey {name} still interested in {street}? Can move fast." If no response in 24 hours: follow up 2.', 'Quick response, willing to discuss price, engagement', 'No response after 48 hours, immediate hard no with no conversation', 'Never - handle this autonomously once trust unlocked', 'A-grade wholesalers respond to direct, confident communication. They deal volume and need reliable buyers. Show you are that buyer.'),
('opening_offer', 'B', 'any', 'First contact with moderately reliable wholesaler', 'More business-focused. Reference your criteria clearly. Dont waste time with someone who wont move.', 'Hey {name} - {address} is in our buy box. Can you work with {our_opening_offer}? We can close in 14 days, cash.', 'Do not invest heavy relationship energy on first deal. Earn trust through performance first.', 'If no response in 6 hours: one follow-up. If no movement after 48 hours, soft no and move on.', 'Willing to negotiate, comes down at least somewhat', 'Refuses to budge, immediately jumps to "I have other buyers"', 'If they counter above MAO', 'B-grade wholesalers need to see you''re serious but also that you won''t overpay. Be efficient.'),
('opening_offer', 'unknown', 'any', 'First contact with wholesaler we have no history with', 'Slightly more cautious. Introduce CCG briefly. Be direct on price. Assess their response quality.', 'Hey {name} - we''re active cash buyers in {county} County. Saw {address} - interested. Can you do {our_opening_offer}? We close fast and clean.', 'Do not explain CCG in detail. Do not get lengthy. Watch out for daisy chain signals.', 'One follow-up maximum at 24 hours if no response.', 'Professional response, willing to discuss, knows their deal', 'Vague responses, cant answer basic questions about the deal, pressure without engagement', 'If deal is above $250K purchase price', 'Unknown wholesalers get evaluated on communication quality in the first exchange. Assess credibility.'),
('counter_above_mao', 'any', 'flip', 'Wholesaler countered above our MAO. Deal is over ceiling.', 'Use comps to justify our position. Never say MAO. Frame it as the math not working. Leave door open.', 'I hear you on the price. We ran the comps - last three 3/2s in that zip sold at {avg_comp}. Our rehab budget is {rehab}. At {their_counter}, the math gets really tight for us. Anything closer to {our_offer} and we can make it work?', 'Do not say "that''s our max." Do not get emotional. Do not escalate into ultimatum territory.', 'If they dont move: soft no. "Not there for us at that number. If anything changes, we''d love another shot."', 'They come down at least 5% toward your number', 'They hold firm and reference another buyer immediately (likely true - walk)', 'If counter is within $10K of MAO and the deal is really strong', 'The comp-based objection is your strongest tool. You''re not being cheap - the market doesn''t support the price.'),
('wholesaler_ghosting', 'any', 'any', 'Sent offer, no response for 4+ hours', 'One direct follow-up. Reference time sensitivity. Dont be needy.', 'Hey {name} - still interested in {address} if it''s available. Can we connect today?', 'Do not send multiple texts in sequence. Do not ask why they havent responded. Do not apologize.', 'If no response after follow-up at 24h: "Hey - going to move on from {address} if we cant connect today. Let me know." Then move on.', 'They respond and re-engage', 'Continued silence after second follow-up', 'Never - this is Adam''s call to make. If 48h no response, mark dead.', 'Wholesalers ghost for many reasons - busy, went with other buyer, deal fell apart. Dont over-pursue. Your time has value.'),
('other_buyer_pressure', 'any', 'any', 'Wholesaler claiming they have another buyer interested', 'Acknowledge it, dont panic, stay at your number. If deal is truly good, slightly increase urgency but not price.', '"Understood - we''re at {our_offer} and thats where the math works for us. If the other offer falls through or doesnt close, we''re here." OR if you want to close: "Okay, we can move to {slightly_higher} if you can give me a signed contract today."', 'Do not immediately jump to MAO. Do not assume they''re bluffing. Do not show desperation.', 'If they go with other buyer: "No worries. Keep us in mind - we close every deal we sign." Track outcome for credibility assessment.', 'They accept your counter or reveal the "other buyer" was pressure tactic', 'They go with other buyer (assess: was price the issue or credibility?)', 'If the deal is exceptional and you want to go to 95%+ of MAO', 'The other-buyer tactic is 50% real, 50% pressure. Stay cool. Your reputation for closing matters more long-term.'),
('pof_request', 'any', 'any', 'Wholesaler or seller requesting proof of funds before discussing price', 'Send POF immediately. Never make them wait for this. Having POF ready = professional credibility.', 'Send the CCG/trust POF letter. "Attached is our proof of funds. We''re ready to move as soon as we align on price."', 'Do not question why they need it. Do not make them ask twice.', NULL, 'They receive it and continue negotiation', 'POF shows amount that doesn''t align with deal size', 'Never - send POF automatically on request', 'POF response time under 10 minutes separates professionals from amateurs. Speed here builds credibility.'),
('arv_pushback', 'any', 'any', 'Wholesaler pushes back on our lower ARV estimate', 'Stand by Urban''s analysis. Reference actual comp sales. Be specific with data. Dont capitulate on ARV without real evidence.', '"We ran the comps specifically - the last 3/2 in that zip sold at {comp1} on {date1} and {comp2} on {date2}. Our ARV of {our_arv} is the supportable number based on what buyers are actually paying. We can''t go off optimistic projections."', 'Do not accept their ARV without evidence. Do not just split the difference to be nice.', NULL, 'They accept Urban''s analysis or provide credible comps that change your view', 'They provide recent comparable sales that genuinely support higher ARV (update Urban)', 'If wholesaler provides comps that legitimately move ARV by more than 5%', 'Data wins. If you have better data, you win. If they have better data, update your position. Never fight data with ego.'),
('soft_no', 'any', 'any', 'Deal doesnt work at current price. Walking away but preserving relationship.', 'Be warm, be brief, leave the door open. They should want to call you first next time.', '"Doesnt work for us at that number, {name}. Keep us in mind - we''re buying every month and we close what we sign. If anything else comes through, shoot it our way."', 'Do not explain your reasoning in detail. Do not be cold or abrupt. Do not burn the bridge.', NULL, 'They keep you in mind for future deals', NULL, 'Never - Adam handles all soft nos autonomously', 'Every soft no is a relationship investment. Do it right every time.'),
('daisy_chain_detected', 'any', 'any', 'Signs that wholesaler doesnt actually control the deal - they are assigning from another wholesaler', 'Ask direct questions about contract control. Request to see their purchase agreement. Be cautious about closing timeline.', '"Hey {name} - quick question: are you the original buyer under contract, or are you assigning from another party? Want to make sure we''re clear on the chain before we move forward."', 'Do not proceed with an offer until chain is understood. Do not commit to a price that doesnt account for multiple assignment fees.', NULL, 'They clearly explain the chain and it''s manageable', 'Vague or evasive answers about who controls the deal', 'Always - Caleb should know when a deal is a daisy chain', 'Daisy chains add closing complexity and risk. Understand the chain. CCG can still do the deal but needs to know.');

-- ── MESSAGE TEMPLATES ────────────────────────────────────────
INSERT INTO message_templates (name, type, channel, wholesaler_grade, deal_type, template, variables, tone, char_count_target, notes) VALUES
('A-Grade Opening SMS', 'opening_offer', 'sms', 'A', 'any', 'Hey {{name}} - saw the {{street}} deal come through. Looks interesting. What''s the best you can do on price? We move fast, cash close.', ARRAY['name','street'], 'direct', 120, 'Short, confident, curious. Do not mention price first. Let them anchor.'),
('B-Grade Opening SMS', 'opening_offer', 'sms', 'B', 'any', 'Hey {{name}} - {{street}} is in our buy box. Can you work with {{opening_offer}}? Cash, can close in 14 days.', ARRAY['name','street','opening_offer'], 'direct', 110, 'More direct on price given less-established relationship. Efficiency matters.'),
('Unknown WS Opening SMS', 'opening_offer', 'sms', 'unknown', 'any', 'Hey {{name}} - we''re active cash buyers in {{county}} County, close on average in 12 days. Interested in {{street}}. Can you work with {{opening_offer}}?', ARRAY['name','county','street','opening_offer'], 'professional', 130, 'Brief credentialing for unknown relationship. Still direct.'),
('Follow-Up 1 - 4hr', 'follow_up_1', 'sms', 'any', 'any', 'Hey {{name}} - still interested in {{street}} if it''s available. Can we connect today?', ARRAY['name','street'], 'casual', 70, '4-hour follow-up. Single line. Not needy. Just keeping communication open.'),
('Follow-Up 2 - 24hr', 'follow_up_2', 'sms', 'any', 'any', 'Going to move on from {{street}} if we can''t connect today, {{name}}. Let me know.', ARRAY['name','street'], 'casual', 75, '24-hour follow-up. Slight urgency. Last contact before moving on.'),
('Counter Below MAO', 'counter_offer', 'sms', 'any', 'any', 'Ran our numbers on {{street}}, {{name}}. Best we can do is {{our_counter}}. Comps don''t support higher - last 3/2 in that zip sold at {{comp_avg}}. If that works, we can sign today.', ARRAY['street','name','our_counter','comp_avg'], 'direct', 155, 'Counter with comp justification. Sign-today urgency.'),
('Soft No - Price Too High', 'soft_no', 'sms', 'any', 'any', 'Doesn''t work for us at that number, {{name}}. Keep us in mind - we''re buying every month and close what we sign. Next one, give us a shot.', ARRAY['name'], 'warm', 130, 'Warm exit. Relationship preservation. Future-focused.'),
('Hard Walk - Final', 'hard_no', 'sms', 'any', 'any', 'Going to pass on {{street}}, {{name}}. Price doesn''t work for our model. Appreciate you sending it.', ARRAY['street','name'], 'professional', 90, 'Clean exit when soft no didnt work. Professional, no explanation needed.'),
('POF Send', 'pof_send', 'sms', 'any', 'any', 'Attached is our proof of funds, {{name}}. Ready to move as soon as we align on price.', ARRAY['name'], 'professional', 85, 'Immediate POF send. Always attach the actual POF document.'),
('Other Buyer - Hold Position', 'counter_offer', 'sms', 'any', 'any', 'Understood, {{name}}. We''re at {{our_offer}} and that''s where the math works. If the other offer falls through, we''re here and can close quick.', ARRAY['name','our_offer'], 'calm', 125, 'Hold position under other-buyer pressure. Calm, confident.'),
('Other Buyer - Slight Bump', 'counter_offer', 'sms', 'any', 'any', 'Okay {{name}}, we can come to {{bumped_offer}} but I need a signed contract today. That''s our ceiling.', ARRAY['name','bumped_offer'], 'urgent', 90, 'Slight bump under genuine other-buyer pressure. Time constraint included.'),
('Relationship Check-In - A Grade', 'relationship_check', 'sms', 'A', 'any', 'Hey {{name}} - been a minute. How''s deal flow looking? We''re buying steady and looking for good stuff in {{county}} County.', ARRAY['name','county'], 'warm', 105, 'Periodic A-grade relationship maintenance. Every 3-4 weeks if no active deal.'),
('Under Contract Notification - Grant', 'under_contract_notify', 'sms', 'any', 'any', 'Grant - {{address}} is under contract at {{price}}. Close date {{close_date}}. Can you coordinate with title?', ARRAY['address','price','close_date'], 'professional', 105, 'Internal notification to Grant when deal is locked.'),
('Wholesale Blast - A Buyers', 'wholesale_blast', 'sms', 'any', 'wholesale', 'Hey {{name}} - have a {{beds}}/{{baths}} {{sqft}}sf {{type}} in {{city}} at {{asking}}. ARV ~{{arv}}, needs ~{{rehab}} work. Interested? First come first served.', ARRAY['name','beds','baths','sqft','type','city','asking','arv','rehab'], 'direct', 155, 'Wholesale deal blast to buyers list. Send to top-matched buyers first.'),
('Buyer Follow-Up', 'buyer_follow_up', 'sms', 'any', 'wholesale', 'Hey {{name}} - following up on {{address}}. Still available if you want to move. Close date is {{close_date}}.', ARRAY['name','address','close_date'], 'casual', 100, 'Follow-up to buyer who showed interest but havent committed.'),
('Daisy Chain Question', 'opening_offer', 'sms', 'unknown', 'any', 'Quick question {{name}} - are you the buyer under contract on {{address}}, or assigning from another party? Want to understand the chain before we move forward.', ARRAY['name','address'], 'professional', 135, 'Direct daisy-chain inquiry. Ask early before investing time.'),
('Dead Deal - Resurrect', 'opening_offer', 'sms', 'any', 'any', 'Hey {{name}} - saw {{address}} is back available. We looked at it {{days}} days ago but price wasn''t there. Still interested if you can get to {{our_offer}}.', ARRAY['name','address','days','our_offer'], 'casual', 135, 'Dead deal resurrection. Reference history. Show consistency.'),
('Deal Accepted Confirmation', 'under_contract_notify', 'sms', 'any', 'any', 'Perfect, {{name}}. Sending the assignment agreement over now. EMD of {{emd}} will wire by {{emd_date}}. Close date of {{close_date}} works for us.', ARRAY['name','emd','emd_date','close_date'], 'professional', 145, 'Confirmation when deal is accepted. Move immediately to paperwork.'),
('Repair Credit Request', 'counter_offer', 'sms', 'any', 'any', '{{name}} - inspector flagged {{issue}}. Need a {{credit}} credit or price reduction to make the numbers work. What can you do?', ARRAY['name','issue','credit'], 'direct', 110, 'Inspection issue repair credit request. Be specific about the issue and amount needed.'),
('EMD Extension Request', 'follow_up_1', 'sms', 'any', 'any', 'Hey {{name}} - need a quick extension on the EMD deadline to {{new_date}}. Title is working through something on our end. Should be clean.', ARRAY['name','new_date'], 'professional', 115, 'EMD extension if needed. Be honest about reason. Most reasonable wholesalers will grant.'),
('New Wholesaler Introduction', 'opening_offer', 'email', 'unknown', 'any', 'Hey {{name}},\n\nHeard good things about the deals you''re finding in {{county}} County. We''re Coralstone Capital Group - active cash buyers doing 3-4 deals a month in {{counties}} Counties. We close on time, every time, and never retrade.\n\nIf you''ve got anything in the pipeline that fits a 3/2+ concrete block profile, shoot it our way. Happy to look same day.\n\nCaleb Blair\nCoralstone Capital Group\n{{phone}}', ARRAY['name','county','counties','phone'], 'professional', 400, 'Cold outreach to new wholesalers. Email format. Professional introduction.'),
('Weekly Pipeline Summary', 'reporting', 'sms', 'any', 'any', '{{name}} - quick pipeline update: {{under_contract}} under contract, {{offers_out}} offers out, {{hot_pending}} HOT deals pending your review. Top priority: {{top_deal}}.', ARRAY['name','under_contract','offers_out','hot_pending','top_deal'], 'professional', 155, 'Weekly summary to Caleb via Telegram. Concise.');

-- ── ADAM TRUST SCORES (INITIAL STATE) ────────────────────────
INSERT INTO adam_trust_scores (action_type, description, category, score, threshold, autonomous, requires_caleb_approval, notes) VALUES
('send_opening_offer_a_grade', 'Send opening offer SMS to A-grade wholesaler', 'outreach', 0, 25, FALSE, TRUE, 'First to unlock. A-grade wholesalers only. After 25 clean approvals.'),
('send_opening_offer_b_grade', 'Send opening offer SMS to B-grade wholesaler', 'outreach', 0, 25, FALSE, TRUE, 'Unlocks after A-grade. B-grade relationships less established.'),
('send_opening_offer_unknown', 'Send opening offer to unknown wholesaler', 'outreach', 0, 35, FALSE, TRUE, 'Higher threshold for unknown relationships. More risk.'),
('send_follow_up_1', 'Send 4-hour follow-up to non-responsive wholesaler', 'outreach', 0, 20, FALSE, TRUE, 'Lower threshold - low-stakes action.'),
('send_follow_up_2', 'Send 24-hour final follow-up', 'outreach', 0, 20, FALSE, TRUE, 'Last contact attempt. Lower stakes.'),
('send_pof', 'Send proof of funds when requested', 'admin', 0, 10, FALSE, TRUE, 'Low risk, should unlock quickly.'),
('send_soft_no', 'Send soft no / walk away message', 'outreach', 0, 15, FALSE, TRUE, 'Relationship-preserving walk. Should unlock early.'),
('send_hard_no', 'Send firm no / deal dead message', 'outreach', 0, 20, FALSE, TRUE, 'More finality. Requires confidence Adam is reading deal correctly.'),
('mark_deal_dead', 'Mark a deal as dead in pipeline', 'admin', 0, 25, FALSE, TRUE, 'Must ensure deal is truly dead before marking. Consult Caleb first.'),
('send_counter_below_mao', 'Send counter offer below MAO', 'negotiation', 0, 30, FALSE, TRUE, 'Price commitment. Never do autonomously early in probation.'),
('send_counter_near_mao', 'Send counter offer within 5% of MAO', 'negotiation', 0, 40, FALSE, TRUE, 'High-stakes price commitment. Higher threshold.'),
('send_wholesale_blast', 'Blast deal to buyers list', 'wholesale', 0, 30, FALSE, TRUE, 'Committing to move a wholesale deal. Need confidence before autonomous.'),
('request_repair_credit', 'Request inspection repair credit from wholesaler', 'negotiation', 0, 25, FALSE, TRUE, 'Post-inspection negotiation. Requires deal context.'),
('send_buyer_followup', 'Follow up with wholesale buyer', 'wholesale', 0, 15, FALSE, TRUE, 'Lower stakes buyer follow-up.'),
('notify_grant', 'Send deal notification to Grant', 'admin', 0, 10, FALSE, TRUE, 'Internal notification. Low risk.'),
('send_deal_accepted_confirm', 'Send deal acceptance confirmation to wholesaler', 'admin', 0, 35, FALSE, TRUE, 'This confirms a contract - high stakes. Late to unlock.'),
('update_pipeline_status', 'Update deal status in Adam database', 'admin', 0, 5, FALSE, TRUE, 'Database update only. Low risk.'),
('post_group_chat_update', 'Post status update to group chat', 'reporting', 0, 5, FALSE, TRUE, 'Informational post only. Low risk.'),
('post_deal_brief', 'Post full deal brief to Caleb Telegram', 'reporting', 0, 8, FALSE, TRUE, 'Deal briefing. Low risk but should be accurate.'),
('send_relationship_checkin', 'Send periodic relationship check-in to wholesaler', 'outreach', 0, 20, FALSE, TRUE, 'Relationship maintenance. Moderate threshold.'),
('request_caleb_approval', 'Request Caleb approval on a deal or action', 'admin', 0, 3, TRUE, FALSE, 'Requesting approval is always autonomous - this is a core function.'),
('log_deal_outcome', 'Log deal outcome and lessons to brain', 'admin', 0, 3, TRUE, FALSE, 'Internal logging - always autonomous.'),
('run_brrrr_analysis', 'Run BRRRR analysis on a deal', 'analysis', 0, 3, TRUE, FALSE, 'Analysis only, no external action. Always autonomous.'),
('run_wholesale_analysis', 'Analyze deal for wholesale potential', 'analysis', 0, 3, TRUE, FALSE, 'Analysis only. Always autonomous.'),
('draft_psa', 'Draft purchase and sale agreement', 'admin', 0, 50, FALSE, TRUE, 'Legal document. Very late to unlock. Requires extensive trust.'),
('send_psa', 'Send PSA to wholesaler for signature', 'admin', 0, 60, FALSE, TRUE, 'Executing a contract. Highest threshold of all actions.');

-- ── MARKET KNOWLEDGE BASE ────────────────────────────────────
INSERT INTO market_knowledge (topic, category, subcategory, content, key_numbers, action_implications, source, confidence, applies_to_counties, applies_to_deal_types, tags) VALUES
-- LEGAL
('Florida Assignment of Contract', 'legal', 'wholesale', 'Florida allows assignment of contracts in real estate unless the original contract explicitly prohibits it. The assignor (CCG/wholesaler) assigns their contractual rights to a buyer in exchange for an assignment fee. The assignee (end buyer) steps into the original contract. A double close is the alternative when disclosure is sensitive.', 'Assignment fee: typically $5,000-30,000. No legal minimum or maximum.', 'Verify assignment clause in every wholesale deal. If "no assignment" language exists, must double close.', 'Florida Statutes', 'high', NULL, ARRAY['wholesale'], ARRAY['wholesale','legal','assignment']),
('Florida Disclosure Requirements', 'legal', 'disclosure', 'Florida Statute 689.261 requires seller to disclose known material defects that affect property value. Includes: mold, roof condition, foundation issues, prior damage, Chinese drywall, HOA issues. As investor buyer you receive disclosure. As seller after flip, you must disclose known issues.', 'Mold must be disclosed if known. Sinkholes must be disclosed per Florida statute.', 'Always document condition at purchase. Photograph everything. Proper disclosure on resale protects from future claims.', 'Florida Statutes 689.261', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas','Polk'], ARRAY['flip','rental','brrrr','wholesale'], ARRAY['legal','disclosure','florida']),
('Florida Sinkhole Disclosure', 'legal', 'disclosure', 'Florida law requires sellers to disclose if a property has had a sinkhole claim or if a sinkhole has been identified. Sinkhole risk varies significantly by county. Hillsborough and Pasco have moderate risk. Hernando has higher risk in some areas. Get sinkhole coverage or inspection on high-risk areas.', 'Sinkhole inspection: $400-700. Sinkhole remediation: $20,000-100,000+.', 'Always ask about prior sinkhole claims. Pull FLDFS sinkhole database. Get geological survey in high-risk areas.', 'Florida Office of Insurance Regulation', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas'], ARRAY['flip','rental','brrrr'], ARRAY['legal','sinkhole','florida','disclosure']),
('Open Permit Risk', 'legal', 'permits', 'Open or expired permits discovered at closing can kill a deal or create significant liability. When a permit is pulled but final inspection never called, it remains open indefinitely. Buyer inherits responsibility. Extremely common in Florida with flipped or improved properties.', NULL, 'Pull permit history on EVERY deal from county building department website before making offer. Negotiate permit resolution into contract. Open permits discovered after closing = your problem.', 'County Building Departments', 'high', NULL, ARRAY['flip','rental','brrrr','wholesale'], ARRAY['legal','permits','due_diligence']),
('HOA in Florida', 'legal', 'hoa', 'Florida HOAs have significant power including foreclosure rights for unpaid dues. Always request HOA estoppel letter showing current status, dues, pending assessments, reserves, and any violations. Rental restrictions are common - always verify if rentals are allowed before buying a rental/BRRRR. Some HOAs have lease approval requirements or minimum lease terms.', 'HOA estoppel fee: $150-500. HOA dues: highly variable $50-500+/month.', 'Always check HOA status before making offer. Ask wholesaler directly. Many HOAs restrict investor activity. CCG tries to avoid HOA properties for rentals.', 'Florida HOA Law Chapter 720', 'high', NULL, ARRAY['rental','brrrr'], ARRAY['hoa','legal','florida']),
('Florida Homestead Exemption - Investor Impact', 'legal', 'tax', 'Properties purchased by non-owner-occupants (investors) do not qualify for homestead exemption ($50,000 exemption). Save Our Homes (SOH) cap (3% annual assessment increase) is also lost when property transfers. New buyer assessed at full market value in purchase year. Significant tax increase vs prior homesteaded owner.', 'Lost homestead = $50K extra assessed value = ~$750-1,500/year additional taxes depending on county millage. SOH cap loss can be substantial on long-held properties.', 'Factor full non-homestead tax assessment into all rental and BRRRR underwriting. Use county property appraiser estimate tool for accuracy.', 'Florida Department of Revenue', 'high', NULL, ARRAY['rental','brrrr'], ARRAY['tax','homestead','florida']),
('Chinese Drywall', 'legal', 'construction', 'Defective Chinese drywall was installed primarily 2004-2008 during building boom. Emits hydrogen sulfide and other sulfur gases. Corrodes copper wiring, AC evaporator coils, electrical connections. Associated with health issues. Required disclosure by law. Remediation costs $50,000-100,000+ typically.', 'Homes most at risk: 2004-2008 construction, builder grade new construction, South Florida origin of materials.', 'For any 2004-2008 construction: smell test (rotten egg odor), check AC coils for black corrosion, check copper wiring. If suspected, get professional inspection. DO NOT BUY without major discount to account for remediation or walk away.', 'Florida Department of Health', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas','Polk'], ARRAY['flip','rental','brrrr'], ARRAY['construction','chinese_drywall','risk','florida']),

-- MARKET DYNAMICS
('Tampa Bay Market Overview 2024-2025', 'market_dynamics', 'overview', 'Tampa Bay remains one of the strongest real estate markets in the US. Migration from Northeast and Midwest continues. Remote work migration has largely settled but demand remains elevated. Rising insurance costs are creating affordability pressure. Condo market experiencing stress from new reserve requirements (SB 4D). Single family homes remain strong. Investor competition has increased significantly vs 2020-2021.', 'Median home price Tampa MSA: ~$400K. YoY appreciation slowing from 20%+ to 5-10%. Inventory rising but still below normal. Days on market increasing.', 'Higher prices make MAO math harder. Focus on off-market and distressed. Relationships with wholesalers are the moat. Speed still matters but not as extreme as 2021.', 'NAR, Zillow, local MLS data', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas','Polk'], ARRAY['flip','rental','brrrr','wholesale'], ARRAY['market','tampa','overview']),
('Florida Insurance Crisis', 'market_dynamics', 'insurance', 'Florida insurance market in significant distress. Multiple carriers have exited Florida. Citizens Insurance (state-backed insurer of last resort) has grown dramatically. Premiums have increased 30-80% in many areas in 2022-2024. Roof age is the primary factor in insurability. Homes with roofs 15+ years old face either very high premiums or difficulty getting coverage. Insurance costs materially affect investor holding costs and buyer purchasing power.', 'Average FL homeowner insurance: $4,500-8,000/year. Coastal: much higher. Roof over 15 years: add $2,000-4,000/year or uninsurable. New roof can reduce premium 15-25%.', 'Always budget realistic insurance costs. New roof pays for itself quickly in insurance savings and marketability. Coastal or flood zone = additional wind/flood coverage required.', 'Florida OIR, industry reports', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas','Polk'], ARRAY['flip','rental','brrrr'], ARRAY['insurance','florida','holding_costs']),
('Pasco County Growth Story', 'market_dynamics', 'county_specific', 'Pasco County is one of the fastest growing counties in Florida. Wesley Chapel, Land O Lakes, and Zephyrhills areas seeing massive new construction and population growth. Retail demand is strong. Older concrete block inventory from 1985-1995 represents the CCG sweet spot - these can be renovated to compete with new construction at significant discount. Infrastructure improvements ongoing. Good schools driving family formation.', 'Pasco population growing 3-5% annually. Wesley Chapel sub-market has seen 15%+ YoY in some zips. Older zips (33525, 33576) still 8-10%.', 'Pasco is CCG primary market for good reason. Focus deals here. Don''t overthink it. Concrete block 85-95 in good school zones are the play.', 'US Census, Pasco County Planning', 'high', ARRAY['Pasco'], ARRAY['flip','rental','brrrr','wholesale'], ARRAY['pasco','growth','market']),
('Spring Hill / Hernando Opportunity', 'market_dynamics', 'county_specific', 'Spring Hill is underappreciated by many Tampa investors. Less competition than Pasco or Hillsborough. Significant inventory of 1980-1995 concrete block. Growing as Tampa overflow market. Primary concerns: many septic systems (budget inspection), some areas have flood zone issues (check FEMA maps), slower appreciation than Pasco but better cashflow math. Strong BRRRR territory.', 'Spring Hill zips: 34606, 34607, 34608, 34609. Median prices $230K-260K. Rents: $1,650-1,750/mo 3BR.', 'Less competition = less urgent timing required. Better cash-on-cash for rental/BRRRR. Budget septic inspection on every deal. Great for patient capital.', 'Local market observation', 'high', ARRAY['Hernando'], ARRAY['rental','brrrr'], ARRAY['hernando','spring_hill','opportunity']),
('Retail vs Investor Buyers by Area', 'market_dynamics', 'buyer_profile', 'Understanding who is buying in each area drives exit strategy. Wesley Chapel, Land O Lakes, Valrico, Brandon: strong retail buyer demand - families relocating for schools and lifestyle. New Port Richey, Spring Hill, older Zephyrhills: more investor buyers, slower retail absorption. Flips in retail buyer areas exit faster and at higher prices. Rentals in investor-heavy areas have more competition for tenant quality.', 'Retail buyer areas: 30-60 DOM avg. Investor-heavy areas: 45-90 DOM avg.', 'Match exit strategy to buyer profile of the area. Dont plan a premium retail flip in an investor-dominated market.', 'MLS data analysis', 'high', ARRAY['Pasco','Hillsborough','Hernando','Pinellas'], ARRAY['flip','rental','brrrr','wholesale'], ARRAY['buyers','market','exit_strategy']),

-- CONSTRUCTION
('Concrete Block vs Frame - Florida Context', 'construction', 'materials', 'Concrete block (CBS - Concrete Block Structure) is significantly superior in Florida for both investment and resale. Better hurricane resistance. Lower insurance premiums (some carriers require CBS or offer discount). Better for Florida climate. Less susceptibility to termites. Slightly higher construction cost but dramatically better long-term. Frame homes are acceptable but CBS preferred.', 'CBS insurance discount: 5-15% depending on carrier. CBS dominates 1960-2000 Florida construction. Newer construction often hybrid.', 'Always prefer CBS. For BRRRR specifically, CBS is required by Caleb''s criteria. For flips, CBS is preferred but frame acceptable with proper due diligence.', 'Florida contractors, insurance carriers', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['construction','concrete_block','florida']),
('Pre-1978 Homes - Lead Paint and Asbestos', 'construction', 'hazmat', 'Homes built before 1978 may contain lead-based paint. Federal law requires disclosure to buyers and specific procedures if disturbing lead paint during renovation. Asbestos was common in floor tiles, ceiling tiles, insulation, and exterior cladding pre-1980. Testing required before disturbing asbestos. Both create cost and liability.', 'Lead paint inspection: $300-400. Asbestos testing: $400-700. Asbestos abatement: $1,000-15,000+ depending on extent.', 'Budget $1,000-2,000 testing contingency on pre-1978 homes. Disclose to end buyer even if abated. Factor abatement cost into rehab budget.', 'EPA, Florida DEP', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['construction','lead_paint','asbestos','pre1978']),
('1978-1999 Construction Sweet Spot', 'construction', 'era', 'This era of construction represents CCG''s ideal target range for buy/hold. CBS construction dominant. Post-1978: lead paint risk eliminated. Post-1980: asbestos largely gone. Pre-2000: homes priced significantly below new construction. Major systems (roof, HVAC, plumbing, electrical) are aged but known - quantifiable rehab. Aluminum wiring risk largely past (peak 1965-1973). Good bones, predictable issues.', 'Typical issues 1978-1999: HVAC 12-18 years (likely needs replacement), roofs 20-30 years (replacement needed), original kitchen/baths (cosmetic update), single-pane windows (upgrade).', 'This is your bread-and-butter property. Model the known capital expenditures. The predictability is the value.', 'CCG operational experience', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['construction','target_era','1978_1999']),
('Aluminum Wiring Risk', 'construction', 'electrical', 'Aluminum wiring was used extensively from approximately 1965-1973 due to copper shortage. Aluminum expands/contracts at different rate than devices, creating loose connections over time - fire hazard. Can be identified by silvery color at receptacle connections. Options: full rewire ($8,000-20,000), pigtailing with COPALUM connectors (proper method but expensive), or AlumiConn connectors (cheaper but requires permits).', 'Full rewire: $10,000-20,000. COPALUM pigtailing: $3,000-8,000. AlumiConn: $2,000-5,000.', 'Check any home built 1965-1973 for aluminum wiring. Most insurance companies require remediation before coverage. Factor cost into deal analysis.', 'CPSC, electrical contractors', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['construction','electrical','aluminum_wiring']),
('Polybutylene Plumbing', 'construction', 'plumbing', 'Polybutylene (PB) pipe was installed primarily 1978-1995 in Florida. Gray plastic pipe. Failed class action settlement in 1995. PB pipe degrades over time from chlorine in water, becomes brittle, fails catastrophically. Now essentially uninsurable or extremely expensive to insure. Full re-pipe required. Immediately disqualifying for many insurance carriers.', 'PB identification: gray plastic pipes, usually gray/silver colored fittings. Full re-pipe cost: $4,000-10,000.', 'Check any 1978-1995 home for PB. Look under sinks, in utility room. If found, deduct re-pipe cost from offer. Disclose to buyer.', 'Insurance industry, plumbing associations', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['construction','plumbing','polybutylene']),

-- FINANCE
('Hard Money Lending Florida', 'finance', 'lending', 'Hard money (HML) lenders provide short-term financing based on asset value rather than borrower creditworthiness. Standard terms in Tampa Bay 2024: 9-10.5% interest only, 1-3 origination points, 90% LTV on purchase, 80% LTV on ARV, 12-month term with extensions available. Draws based on rehab progress with inspection required. 3-7 business day funding typical. ENTITY REQUIRED - must close in LLC or trust.', 'CCG standard HML assumption: 9.5% interest, 2 points, 90% LTV. Monthly interest on $250K loan: ~$1,979/month.', 'Always use HML for flips unless RLOC cost is lower. RLOC at prime may be cheaper than HML - compare rates. Budget 4-5 months interest on every flip (dont use 3 month assumption - projects run long).', 'Tampa Bay HML lender landscape', 'high', NULL, ARRAY['flip','wholesale'], ARRAY['finance','hml','lending']),
('DSCR Loans for BRRRR/Rental', 'finance', 'lending', 'Debt Service Coverage Ratio (DSCR) loans qualify based on property income vs debt payment, not personal income. Ideal for investors. No tax returns required. Standard terms: 6.5-7.5% fixed rate (2024-2025), 75-80% LTV, 30-year amortization. DSCR must be 1.0-1.25x depending on lender. Rate varies with LTV, credit score, DSCR ratio.', 'CCG DSCR assumption: 6.75% rate, 75% LTV, 30-year. Monthly P&I on $180K loan: ~$1,168/month. DSCR requirement: typically 1.0x (rent >= payment).', 'Model all rentals and BRRRR at 6.75% DSCR, 75% LTV. If deal doesnt cash flow at these rates, its a pass for hold. Check current rates before committing - model conservatively.', 'Mortgage market observation', 'high', NULL, ARRAY['rental','brrrr'], ARRAY['finance','dscr','lending','brrrr']),
('CCG 20-Million RLOC Strategy', 'finance', 'ccg_specific', 'CCG has access to a $20M revolving line of credit (RLOC). This provides significant acquisition firepower. RLOC cost vs HML cost should be compared on every deal. RLOC provides speed advantage - can close in 1-3 days on right deal vs 5-7 for HML. RLOC also enables purchasing multiple simultaneous deals. Critical strategic advantage.', 'RLOC available: ~$20M. Current RLOC rate: compare to HML. HML: 9.5% + 2 points. If RLOC is cheaper, use RLOC.', 'Always know current RLOC availability and rate. If RLOC is cheaper than HML, recommend it. Speed advantage for hot deals. Monitor total deployment.', 'CCG internal', 'high', NULL, ARRAY['flip','rental','brrrr','wholesale'], ARRAY['finance','rloc','ccg','capital']),
('Closing Costs - Florida Investor Buyer', 'finance', 'closing', 'Florida closing costs for investor buyers (non-owner): title search and insurance (0.5-1% of price), doc stamps on deed ($0.70/$100 purchase price), doc stamps on mortgage ($0.35/$100 loan amount), intangible tax on mortgage (0.002 x loan amount), recording fees ($10-30/page), lender fees, attorney/title company fees. Total: typically 1-3% of purchase price.', 'Example $200K purchase: doc stamps deed = $1,400. Doc stamps mortgage = $700 (on $180K loan). Intangible tax = $360. Title insurance = $1,000-1,500. Total closing costs: ~$3,500-4,500.', 'Budget 2% of purchase price for buyer closing costs in deal underwriting. Dont forget this in all-in cost calculation.', 'Florida Statute 201.02', 'high', NULL, ARRAY['flip','rental','brrrr','wholesale'], ARRAY['finance','closing_costs','florida']),
('Selling Costs - Florida Flip', 'finance', 'closing', 'When selling a flipped property in Florida: agent commissions 5-6% (2.5-3% each side), closing costs 1-2% paid by seller, title insurance for buyer (seller typically pays in FL), doc stamps on deed ($0.70/$100), any negotiated repairs or credits. Total: typically 7-9% of sale price. CCG model uses 7.5% selling costs.', 'On $300K sale: agent commission 6% = $18K. Closing costs 1.5% = $4,500. Total out: ~$22,500 (7.5%).', 'Use 7.5% selling costs in all underwriting. Never use less than 7%. Some deals command higher commissions in new areas.', 'Florida real estate practice', 'high', NULL, ARRAY['flip','wholesale'], ARRAY['finance','selling_costs','commissions']),

-- INSURANCE
('Four-Point Inspection Requirement', 'insurance', 'requirements', 'Most Florida insurance carriers require a four-point inspection for homes 25+ years old (built before 2000 in 2025). The inspection covers: roof (age/condition), HVAC (age/type/condition), plumbing (material/condition), electrical (panel brand/condition). Results directly impact insurability and premium. Homes with poor four-point scores may be difficult to insure.', 'Four-point inspection cost: $150-250. Failing items: Federal Pacific panel, aluminum wiring, polybutylene pipe, roof 20+ years.', 'Get four-point inspection on any pre-2000 home before closing. Red flags can be negotiated into price. Know what you''re buying before you commit.', 'Florida insurance carriers', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['insurance','four_point','florida']),
('Wind Mitigation Inspection Value', 'insurance', 'savings', 'Wind mitigation inspections document protective features of a home to qualify for insurance discounts. Credits for: hip roof (vs gable), roof covering type, roof deck attachment, roof-to-wall connection (hurricane straps), opening protection (impact windows/shutters). Can reduce wind premium 20-40%.', 'Wind mitigation inspection: $100-200. Premium savings: $500-2,000+/year depending on features.', 'Always get wind mitigation inspection after rehab. New roof, impact windows, and hurricane straps dramatically reduce premiums. Provide inspection to listing agent for buyer marketing advantage.', 'Florida OIR', 'high', NULL, ARRAY['flip','rental','brrrr'], ARRAY['insurance','wind_mitigation','savings']),
('Flood Zone Impact on Investment', 'insurance', 'flood', 'FEMA flood zone designations significantly affect investment viability. Zone X (minimal risk): standard home insurance sufficient. Zone AE (high risk): flood insurance required by lenders. Average NFIP flood policy: $2,000-8,000/year depending on value and zone. Coastal properties may require private flood coverage. Flood zone designation affects buyer pool and resale value.', 'NFIP flood insurance: ~$1,200/year average nationally but much higher in high-risk FL. Private flood insurance: often cheaper but less predictable.', 'Check flood zone on every deal via FEMA FIRMette map before making offer. Zone AE = significant additional holding cost. Budget flood insurance in all-in analysis on any non-X zone property.', 'FEMA flood maps', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas'], ARRAY['flip','rental','brrrr','wholesale'], ARRAY['insurance','flood','fema','risk']),

-- TAX
('Property Tax Estimation Florida', 'tax', 'estimation', 'Florida property tax = Assessed Value x Millage Rate. As investor (non-homestead), assessed value = purchase price in first year. Millage rates by county: Hillsborough ~17-20 mills, Pasco ~18-21 mills, Hernando ~16-18 mills, Pinellas ~18-22 mills. Formula: (Purchase Price / 1000) x Millage Rate = Annual Tax.', 'Example: $250K home in Hillsborough at 19 mills = ($250,000/1,000) x 19 = $4,750/year = $396/month. Check HCPA.net for Hillsborough, PCPAO.org for Pasco, hernandopa.com for Hernando.', 'Use county property appraiser website for accurate estimates. Always budget non-homestead rate (purchase price x effective rate). Include in monthly hold cost calculation for rentals and BRRRR.', 'County property appraisers', 'high', ARRAY['Hillsborough','Pasco','Hernando','Pinellas'], ARRAY['rental','brrrr','flip'], ARRAY['tax','property_tax','estimation']),

-- DEAL STRATEGY
('The 70% Rule Explained', 'ccg_strategy', 'underwriting', 'CCG uses MAO = ARV x 70% - Repairs. This formula ensures minimum 10-15% profit margin after all costs. At 70% ARV minus repairs, assuming 7.5% selling costs, 4-5% financing, 3-4% holding costs, and the rehab itself, the net profit should be 8-12% of ARV ($25K-35K on a $300K ARV deal). This rule holds across market conditions because it bakes in the unknowns.', 'MAO example: $285K ARV, $40K repairs = ($285K x 0.70) - $40K = $199,500 - $40K = $159,500 MAO. Opening offer: $159,500 x 0.88 = $140,360.', 'Never offer above MAO. Opening offer at 88% of MAO. Hold firm above 94%. Walk above MAO unless extraordinary circumstances and Caleb personally approves.', 'Real estate investment principles', 'high', NULL, ARRAY['flip','wholesale'], ARRAY['underwriting','mao','70percent_rule']),
('BRRRR Math and Cash Left In', 'ccg_strategy', 'underwriting', 'BRRRR success metric: how much cash is left in the deal after refinance. Total cash in = purchase price + rental rehab costs. Cash returned = ARV x refi LTV (75%). Cash left in = Cash in - Cash returned. If negative: you made money AND own the property. Under 20% left in = strong BRRRR. Under 10% = excellent. Zero or negative = unicorn.', 'Example: Buy $160K + $20K rehab = $180K in. ARV $255K x 75% = $191K refi. Cash left in = $180K - $191K = -$11K (got cash OUT plus property). Unicorn deal.', 'Every BRRRR deal must be modeled to cash left in percentage. Target under 20%. Model at conservative ARV (use Urban''s number, not wholesaler''s).', 'BRRRR investment strategy', 'high', NULL, ARRAY['brrrr'], ARRAY['brrrr','underwriting','cash_left_in']),
('Wholesale Assignment vs Double Close', 'ccg_strategy', 'wholesale', 'Assignment: CCG assigns its purchase contract to end buyer. Assignment fee is paid at closing. Simple, cheap, but discloses CCG''s purchase price to end buyer. Double close: CCG actually purchases with A-to-B transaction, then immediately sells to end buyer in B-to-C transaction. More expensive (two closings, two title policies) but protects spread privacy. Some title companies wont do double closes.', 'Assignment fee: no title insurance cost. Double close: additional $2,000-4,000 in title and closing costs but spread is protected.', 'Default to assignment for deals where spread is reasonable and relationship allows. Use double close when spread is large (>$25K) and you need to protect the margin.', 'Real estate wholesale practice', 'high', NULL, ARRAY['wholesale'], ARRAY['wholesale','assignment','double_close']),
('Deal Velocity - Why Speed Matters', 'ccg_strategy', 'operations', 'In the Tampa Bay wholesale market, the best deals typically have 2-5 competing buyers. Wholesalers test buyers on response time and close capability. CCG''s competitive advantage is: (1) clarity on price, (2) response within hours not days, (3) reputation for closing what we sign, (4) Adam enabling 24/7 response. Every hour of delay on a HOT deal increases risk of losing to a competitor.', 'Target: offer sent within 30 min of deal arriving as HOT. First response to wholesaler within 15 minutes during business hours.', 'Adam''s core value prop is speed without Caleb having to be available 24/7. Probation system ensures quality. Speed kills competition.', 'Market observation', 'high', NULL, ARRAY['flip','rental','brrrr','wholesale'], ARRAY['strategy','speed','competitive_advantage']);

-- ── PROPERTY TAX DATA ────────────────────────────────────────
INSERT INTO property_tax_data (county, millage_rate_per_1000, effective_rate_pct, assessment_ratio, homestead_exemption_amount, investor_no_homestead_notes, investor_effective_rate_pct, estimate_formula, assessor_website) VALUES
('Hillsborough', 19.2, 1.92, 100, 50000, 'Non-homestead: assessed at purchase price. No SOH cap until 2nd year. Effective rate on investment property ~1.9-2.0%.', 1.95, '(Purchase Price / 1000) * 19.2 = Annual Tax', 'https://www.hcpafl.org'),
('Pasco', 19.8, 1.98, 100, 50000, 'Pasco non-homestead slightly higher than Hillsborough. Similar structure.', 2.00, '(Purchase Price / 1000) * 19.8 = Annual Tax', 'https://www.pascopa.com'),
('Hernando', 17.5, 1.75, 100, 50000, 'Hernando lower millage than Tampa core counties. Advantage for investors holding rentals.', 1.78, '(Purchase Price / 1000) * 17.5 = Annual Tax', 'https://www.hernandopa.org'),
('Pinellas', 20.1, 2.01, 100, 50000, 'Pinellas has higher millage. Factor into rental underwriting.', 2.05, '(Purchase Price / 1000) * 20.1 = Annual Tax', 'https://pcpao.gov'),
('Polk', 16.8, 1.68, 100, 50000, 'Polk County lower taxes benefit investor math.', 1.70, '(Purchase Price / 1000) * 16.8 = Annual Tax', 'https://qpublic.schneidercorp.com/Application.aspx?AppID=838'),
('Sarasota', 18.5, 1.85, 100, 50000, 'Sarasota moderate millage but higher property values create higher absolute tax.', 1.88, '(Purchase Price / 1000) * 18.5 = Annual Tax', 'https://www.sc-pa.com');

-- ── INSURANCE DATA ───────────────────────────────────────────
INSERT INTO insurance_data (county, property_type, construction_type, avg_annual_premium, min_annual_premium, max_annual_premium, wind_mitigation_discount_pct, four_point_required_year_built, market_notes, notes) VALUES
('Hillsborough', 'SFR', 'concrete_block', 3800, 2200, 8000, 22, 2000, 'Market tightening. Some carriers exiting. Citizens growing. Roofs over 15 years difficult to insure with some carriers.', 'CBS with new roof and hip design can get below $2,500/yr. Frame with old roof can exceed $7,000/yr. Shop carriers aggressively.'),
('Hillsborough', 'SFR', 'frame', 4800, 3000, 10000, 18, 2000, 'Frame homes cost more to insure than CBS in Florida. Some carriers now declining frame entirely.', 'Frame homes in flood zone can be very expensive or uninsurable.'),
('Pasco', 'SFR', 'concrete_block', 3500, 2000, 7500, 22, 2000, 'Pasco slightly less expensive than Hillsborough. Similar market trends.', 'Coastal Pasco (Hudson, Port Richey) significantly more expensive due to wind zone.'),
('Pasco', 'SFR', 'frame', 4500, 2800, 9500, 18, 2000, NULL, 'Avoid frame in coastal Pasco - insurance often exceeds budget.'),
('Hernando', 'SFR', 'concrete_block', 3200, 1800, 7000, 20, 2000, 'Hernando generally less expensive than Tampa core. Growing availability.', 'Spring Hill inland: good insurance market. Coastal Spring Hill: more expensive.'),
('Pinellas', 'SFR', 'concrete_block', 5500, 3500, 15000, 25, 2000, 'Pinellas most expensive in CCG territory due to wind exposure and flood risk. Some coastal areas very difficult to insure.', 'Inland Pinellas (Largo, Pinellas Park) more manageable. Beach areas can exceed $20K/yr.'),
('Polk', 'SFR', 'concrete_block', 2800, 1600, 6000, 18, 2000, 'Polk County less expensive - further from coast, less wind exposure.', 'Better insurance economics support better cashflow math for rentals.');

-- ── TITLE COMPANIES (PLACEHOLDER STRUCTURE) ─────────────────
INSERT INTO title_companies (name, counties, investor_friendly, avg_close_days, simultaneous_close_capable, assignment_friendly, notes) VALUES
('TBD - Pasco Primary', ARRAY['Pasco'], TRUE, 14, TRUE, TRUE, 'Caleb to add preferred Pasco title company. Key: investor friendly, simultaneous closes, assignment OK.'),
('TBD - Hillsborough Primary', ARRAY['Hillsborough'], TRUE, 14, TRUE, TRUE, 'Caleb to add preferred Hillsborough title company.'),
('TBD - Hernando Primary', ARRAY['Hernando'], TRUE, 16, TRUE, TRUE, 'Caleb to add preferred Hernando title company. Spring Hill area specialist preferred.');

-- ── HARD MONEY LENDERS (FRAMEWORK) ──────────────────────────
INSERT INTO hard_money_lenders (name, interest_rate_pct, origination_points, max_ltv_purchase, max_ltv_arv, term_months, draws_available, draw_inspection_required, draw_turnaround_days, relationship_status, notes) VALUES
('Coralstone Lending (Internal)', 9.0, 1.5, 90, 75, 12, 4, TRUE, 2, 'active', 'CCG internal lender. Check capacity first before going to external HML. Caleb to specify current terms and capacity.'),
('TBD External HML 1', 9.5, 2.0, 90, 80, 12, 4, TRUE, 5, 'active', 'Caleb to add primary external HML relationship. Standard Tampa Bay HML terms as placeholder.'),
('TBD External HML 2', 10.0, 2.0, 85, 75, 12, 4, TRUE, 5, 'backup', 'Caleb to add backup HML. Good to have 2-3 relationships for volume deals.');

-- ── INITIAL ADAM LEARNINGS ───────────────────────────────────
INSERT INTO adam_learnings (type, context, lesson, confidence, applies_to) VALUES
('market_pattern', 'Tampa Bay market 2024-2025', 'Speed and certainty of close matter as much as price in competitive wholesale markets. Wholesalers choose reliable buyers over highest bidders.', 'high', ARRAY['wholesale','negotiation']),
('market_pattern', 'Concrete block preference', 'CCG specifically targets concrete block construction. When evaluating deals, CBS is not just preferred - for BRRRR it is required. Always identify construction type early in evaluation.', 'high', ARRAY['brrrr','flip']),
('market_pattern', 'Florida insurance impact', 'Insurance costs are now a significant variable in Tampa Bay investment math. Roof age is the primary driver. New roof can swing deal economics by $200-400/month in holding costs.', 'high', ARRAY['rental','brrrr','flip']),
('negotiation_outcome', 'Opening offer strategy', 'Open at 88% of MAO. This leaves room to negotiate while still being in range. Opening at 85% or below often loses deals to other buyers in competitive market. Opening at 92%+ leaves no room.', 'high', ARRAY['negotiation','flip','brrrr']),
('market_pattern', 'Pasco County positioning', 'Pasco is CCG primary territory for multiple reasons: older CBS inventory, growth-driven retail exit demand, strong rental market, less competition than Hillsborough core. Prioritize Pasco leads.', 'high', ARRAY['flip','brrrr','rental']),
('market_pattern', 'Hernando spring hill brrrr', 'Spring Hill (Hernando County) has better BRRRR math than most Hillsborough due to lower prices and reasonable rents. The tradeoff is slower appreciation and septic systems. Right for patient capital.', 'high', ARRAY['brrrr','rental']),
('deal_outcome', 'Rehab contingency importance', 'Florida homes consistently have hidden issues discovered during rehab. A 10-15% contingency is not optional - it is a predictable cost. Deals analyzed without contingency routinely disappoint.', 'high', ARRAY['flip','brrrr','rental']);

COMMIT;
